- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- README.md
I've made a start on the documentation for the proposal process, I'm then going to propose a few components to see how the process feels.
> Document the proposal process

- proposals/accepted/0000-npm.md
(i guess `^` is an org mode thing? it's not supported in GFM)
> fix superscript syntax

- proposals/accepted/0000-npm.md
see comments: https://github.com/Financial-Times/origami/pull/86
> misc npm proposal changes

- scripts/regenerate-ci-config-files.js
> chore: fix bootstrap-sha in release-please template

- .github/labeler.yml
- templates/labeler.yml
> update labeler to use plural labels

- components/o-autocomplete/README.md
- components/o-big-number/README.md
- components/o-buttons/README.md
- components/o-cookie-message/README.md
- components/o-date/README.md
- components/o-editorial-typography/README.md
- components/o-expander/README.md
- components/o-footer/README.md
- components/o-labels/README.md
- components/o-normalise/README.md
- components/o-overlay/README.md
- components/o-share/README.md
- components/o-subs-card/README.md
- components/o-table/README.md
- components/o-tabs/README.md
- components/o-teaser-collection/README.md
- components/o-teaser/README.md
- components/o-topper/README.md
- components/o-typography/README.md
- components/o-video/README.md
> fix all the readmes

- components/o-header/demos/src/grid-demo.mustache
- components/o-header/demos/src/header.json
- components/o-header/demos/src/header.mustache
- components/o-header/demos/src/mega-menu.json
- components/o-header/demos/src/pa11y.mustache
- components/o-header/demos/src/simple-header.mustache
- components/o-header/demos/src/sticky-header.mustache
- components/o-header/demos/src/subbrand.json
- components/o-header/demos/src/subbrand.mustache
- components/o-header/demos/src/subnav-right-align.json
- components/o-header/demos/src/subnav.json
- components/o-header/demos/src/transparent-header.json
Remove an extra closing `li` tag and ensure unique ids.
> fix: correct markup in o-header demos

- CONTRIBUTING.md
- README.md
This adds some very basic documentation. we'll need to fill this out more as we progress
> docs: start adding docs

- apps/storybook/addons/guidelines/package.json
- apps/storybook/addons/html/package.json
- apps/storybook/addons/markdown-tabs/package.json
- apps/storybook/package.json
- libraries/o-utils/package.json
- presets/eslint-config-origami-component/package.json
- presets/remark-preset-lint-origami-component/package.json
- presets/stylelint-config-origami-component/package.json
- tools/a11y/package.json
- tools/origami-build-tools/package.json
This is more honest. We use `--if-present` in the workflows now, so these won't fail by being missing.
> Remove lint and test skip scripts

- apps/website/_components/customisation.md
- apps/website/_includes/demo.html
build service v3 does not allow for a "latest" version
> fix: add version to website component demo

- apps/website/_includes/demo.html
How many Lees does it take to change a lightbulb? Let's try again.
I'm putting off installing rvm / ruby / blah blah on my new machine 
and therefore didn't check the request was right 🙈
> fix: website build service demo request

- README.md
- components/o-subs-card/.github/CODEOWNERS
- components/o-subs-card/.github/ISSUE_TEMPLATE.md
- components/o-subs-card/.github/workflows/add-new-issues-and-pull-requests-to-origami-project-board.yml
- components/o-subs-card/.github/workflows/apply-labels.yml
- components/o-subs-card/.github/workflows/auto-approve.yml
- components/o-subs-card/.github/workflows/automatic-tag-and-release.yml
- components/o-subs-card/.github/workflows/percy.yml
- components/o-subs-card/.github/workflows/publish-to-npm-as-latest.yml
- components/o-subs-card/.github/workflows/publish-to-npm-as-prerelease.yml
- components/o-subs-card/.github/workflows/sync-repo-labels.yml
- components/o-subs-card/.github/workflows/test-origami-component.yml
- components/o-subs-card/MIGRATION.md
- components/o-subs-card/README.md
- components/o-subs-card/app.json
- components/o-subs-card/demos/src/demo.mustache
- components/o-subs-card/demos/src/pa11y.mustache
- components/o-subs-card/main.js
- components/o-subs-card/main.scss
- components/o-subs-card/package.json
- components/o-subs-card/src/js/subsCard.js
- components/o-subs-card/src/scss/_mixins.scss
- components/o-subs-card/test/helpers/fixtures.js
- components/o-subs-card/test/subsCard.test.js
- scripts/component/lint.bash
o-subs-card was originally imported in an in-between state
> re-import o-subs-card v6

- components/o-subs-card/package.json
- package-lock.json
it uses o-normalize, but it doesn't tell anyone!!!!!
> fix: add o-subs-card normalize trans dependency

- components/o-layout/test/helpers/fixtures.js
- components/o-layout/test/layout.test.js
The fixture is now closer to what would be written in a real-world
project, projects are not only a set of headings, they also have
paragraphs.
This is staying as a draft until I prove that the tests can pass 1000 times in a row
> backstage: add content to the layout sections and decrease viewport

- scripts/percy.js
this is all handled within obt demo now instead, which is great
> fix: stop building specific demos for each brand in percy

- components/o-viewport/src/utils.js
- package-lock.json
- package.json
must have missed this one
closes #455
> fix linting in o-viewport

- components/o-date/package.json
- package-lock.json
- package.json
hooray! it worked really easily that time for some reason
> Upgrade to npm@8 and a newer Node.JavaScript

- components/o-toggle/origami.json
I tested this locally by using the changes in #560 which adds polyfiill.io urls to local demos
> o-toggle: add/correct all the required features to get demos working in ie11

- components/o-cookie-message/src/tsx/cookie-message.tsx
- components/o-cookie-message/stories/cookie-message.stories.tsx
- package-lock.json
The cookie message gets removed when the button is clicked, which confuses React. Wrap it in a div so there is a node to remove when switching between similar doms.
this is the commit to look at:
https://github.com/Financial-Times/origami/pull/572/commits/92a39f577dba72df8beb74d4a5de4d343c97ee9d
> Wrap cookie message in a div so there is something to remove

- package-lock.json
This should fix this error --> https://github.com/Financial-Times/origami/runs/4883858997?check_suite_focus=true
> backstage: recreate the lockfile to try and fix the issue on ci

- apps/website/_posts/2021-07-01-origami-on-npm-and-how-to-migrate.md
it doesn't have a migration guide
> Add n-notification to the bower versions list

- apps/website/_components/code.md
What?
Corrected Domain name for HTML living standard
Why?
Broken link
> Link Correction

- components/o-layout/README.md
I used sidebar nav for the first time today and couldn't get it to work until I added this. Not sure if these instructions are elsewhere but I didn't see them in the readme
> docs: update o-layout Readme instructions on how to use sidebar nav

- components/o-forms/README.md
- components/o-forms/demos/src/data/checkboxes.json
- components/o-forms/demos/src/data/toggle.json
- components/o-forms/demos/src/multiple-input-field.mustache
- components/o-forms/src/scss/_checkbox.scss
- components/o-forms/src/scss/_select.scss
- components/o-forms/src/scss/_toggle.scss
- components/o-forms/src/scss/modifiers/_custom.scss
- components/o-forms/src/scss/modifiers/_inverse.scss
- components/o-forms/src/scss/shared/_base.scss
- components/o-forms/src/scss/shared/_control-inputs.scss
- components/o-forms/src/scss/shared/_variables.scss
- Add support for toggle / checkbox descriptive text.
- Add cross/tick icons to toggle checkboxes.
- Fix inverse theme for toggle checkboxes.
> feat: checkbox descriptive text + toggle checkbox improvements

- components/g-audio/README.md
- components/g-audio/main.js
- components/g-audio/src/js/audio.js
> fix: Fix g-audio init

- components/o-header/demos/src/header.mustache
- components/o-header/main.scss
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_transparent.scss
Add some CSS needed for a new component in drawer menu.
See https://github.com/Financial-Times/dotcom-page-kit/pull/940 for further details
> ACQ-1536: add some css needed for new drawer menu component

- package-lock.json
- package.json
- scripts/percy.js
This figures out which components across the whole monorepo are affected by a change.
E.G. If o-spacing has changed, this will run n-notifications Percy even though n-notification does not directly depend on o-spacing. It runs because n-notification depends on o-typography which depends on o-spacing
> Run Percy if a package has a dependency within origami which has changed comapred to the main branch

- .github/CODEOWNERS
> Add the o-tracking codeowner

- components/o-buttons/src/scss/_brand.scss
These are being added to the Figma UI Kit
> feat: o-buttons add ghost mono / inverse themes

- components/o-layout/src/scss/_grid.scss
I am actually just interested in triggering an automated release.
> fix: o-layout, use o-colors to get "white" hex

- apps/website/_services/bower-registry.md
- apps/website/pages/documentation.html
Respect post "collection_listing_display" setting. Update Bower page, decommissioned.
> docs: Update Origami documentation lists

- components/o-footer/demos/src/simple-footer.mustache
relates to: 73bc1c6e3e75a677602fd3051c4ea9f9f72f360d
> fix: Add another missing Slavery Statement & Policies link

- apps/website/scripts/email-newsletter.js
MarTech have switched to Mailgun
> backstage: blog, migrate to new email service

- components/o-forms/demos/src/interactive-suffix.mustache
- components/o-forms/demos/src/single-input-field.mustache
> 544 dac suffix input fix

- .github/workflows/percy.yml
- .github/workflows/test.yml
- components/o-forms/demos/src/interactive.mustache
- components/o-forms/demos/src/inverse-form.mustache
- components/o-forms/package.json
- components/o-forms/src/js/error-summary.js
- components/o-forms/src/js/forms.js
- components/o-forms/src/scss/shared/_error-summary.scss
- package-lock.json
- templates/percy-workflow.yml
- templates/test-workflow.yml
- feat: update o-colors to fix bg color
- feat: add custom optional message to error summary
- feat: add alert icon to error summary
https://financialtimes.atlassian.net/browse/ACQ-1918
> Update error summary message for o-forms

- components/o-forms/src/js/input.js
Previously it would always show an error when filling out the date field,
even before trying to give a month or year.
I'm not sure `Date.parse` was catching any errors that the regex isn't, and therefore we could simplify? 
In Firefox for example it's still possible to pass "31/11/2022" which is not actually a valid date. We could 
include a library to improve the validation further but perhaps should leave that for back-end logic for now?
This change also handles date fields which don't include all the inputs
before:
after:
> backstage: Do not validate o-forms date field before user has attempted each input.

- components/o-header-services/.npmignore
We're writing and reviewing tsx with the user in mind, so let's publish new tsx straight away from now on 😄
> feat: publish o-header-services tsx

- components/o-header/demos/src/grid-demo.mustache
- components/o-header/demos/src/header.mustache
- components/o-header/demos/src/pa11y.mustache
- components/o-header/demos/src/simple-header.mustache
- components/o-header/demos/src/sticky-header.mustache
- components/o-header/demos/src/subbrand.mustache
- components/o-header/src/tsx/drawer.tsx
- package-lock.json
update o header close button label and title so it matches open menu label; closes #901
> backstage: remedy o header DAC issues

- components/o-topper/demos/src/deep-portrait.mustache
- components/o-topper/origami.json
- components/o-topper/src/scss/_mixins.scss
- components/o-topper/src/scss/_variables.scss
- package-lock.json
[ticket](https://financialtimes.atlassian.net/browse/CI-1411)
> [CI-1411] Deep Portrait: topper name changed

- components/o-topper/package.json
- package-lock.json
[ticket](https://financialtimes.atlassian.net/browse/CI-1411)
> [CI-1411] Deep Portrait: update n-map-content-to-topper to 3.2.0

- components/o-video/src/js/video.js
comment progress video track on 100%.
> fix: o-video track comment

- components/o-big-number/.npmignore
i want this big number!!!! can i have it?
> feat: allow big-number's tsx to be published

- components/o-comments/src/scss/coral-talk-iframe/main.scss
[ticket](https://financialtimes.atlassian.net/browse/CI-1530)
> [CI-1530] coral font size for content

- README.md
Testing a Jira integration. Let's add an oxford comma. Both me and Thérèse Coffey are a fan, but otherwise we probably have little in common
> docs: add oxford comma

- components/o-forms/README.md
- package-lock.json
Trigger a release. For some reason release-please did not detect the last commit as a user facing change https://github.com/Financial-Times/origami/actions/runs/4261001466/jobs/7414809458
> feat: o-forms, allow submit events to be intercepted

- apps/website/assets/images/2023-03-03-newsletter/o-multi-select.png
> chore: introduce newsletter image asset

- components/o-date/MIGRATION.md
- components/o-date/README.md
Update migration docs for breaking change of o-date v6.
> Update o date migration guide v6

- components/o-topper/src/scss/themes/_deep-landscape.scss
change opacity to 0.67 on black background box and 0.7 on white background box
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?modal=detail&selectedIssue=CI-1619)
> fix: change opacity background box

- .github/workflows/percy.yml
- .github/workflows/test.yml
- templates/percy-workflow.yml
- templates/test-workflow.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths
> backstage: only run tests when relevant files change

- components/o-header-services/README.md
closes: https://github.com/Financial-Times/origami/issues/214
> docs: improve markup guidence around aria labels [OR-64]

- components/o-forms/README.md
- components/o-multi-select/src/js/multi-select-options.js
but also fixes markdown violations for o-forms readme
> feat: fake commit to publish tsx templates

- components/o-banner/README.md
- components/o-banner/demos/src/professional-inverse.mustache
- components/o-banner/demos/src/professional.mustache
- components/o-banner/origami.json
- components/o-banner/src/scss/_brand.scss
- components/o-banner/src/scss/_mixins.scss
- components/o-banner/src/scss/_variables.scss
- components/o-banner/src/scss/themes/_theme.scss
- components/o-banner/src/tsx/banner.tsx
> feat: o-banner, add FT Professional theme [OR-164]

- components/o-top-banner/main.scss
- components/o-top-banner/origami.json
- components/o-top-banner/package.json
- package-lock.json
Re-open a branch to fix issues for [auto merged PR](https://github.com/Financial-Times/origami/pull/1142)
> O top banner fix deps

- .github/workflows/test.yml
- components/o-normalise/README.md
- package-lock.json
- templates/test-workflow.yml
This PR should help us to simplify and improve performance of our CI pipeline. We are implementing [Paths Changes Filter](https://github.com/marketplace/actions/paths-changes-filter#examples) action to detect changes in component folders and based on those changes to trigger tests or not.
> backstage: improve CI and dont run component tests if not needed

- components/o-video/src/scss/_guidance.scss
removed a deprecated parameter
hmm?
???
> fix: Remove deprecated $external parameter from otypographylink call

- .github/workflows/test.yml
- components/o-buttons/README.md
- templates/test-workflow.yml
> fix: introduce designer guidelines to o-buttons readme

- components/o-forms/README.md
- components/o-labels/README.md
- components/o-social-follow/README.md
Reverts Financial-Times/origami#1182
> Revert "Fix/migrate designer docs to component readmes"

- .github/workflows/test.yml
- templates/test-workflow.yml
> backstage: check test results for branch-protection gate

- scripts/build-website.bash
fixes memory issues when building using Astro by bumping heap
> fix: fatal error on publish

- .github/workflows/build-websites.yml
- apps/astro-website/src/pages/blog/index.astro
FIx broken links for blog posts
> fix: broken urls for blogposts

- apps/dictionary/README.md
Preliminary readme for Origami Dictionary documenting the steps to get set up in order to work with our design tokens.
> docs: introduce getting started guide for origami dictionary

- apps/dictionary/tokens/$metadata.json
- apps/dictionary/tokens/components/o-buttons/tokens.json
Push tokens for buttons so we can sync them with Figma
[OR-285](https://financialtimes.atlassian.net/jira/software/c/projects/OR/boards/1658?modal=detail&selectedIssue=OR-285)
[OR-285]: https://financialtimes.atlassian.net/browse/OR-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: generate tokens for button component

- components/o3-button/stories/buttons-professional.scss
- components/o3-button/stories/buttons-professional.stories.tsx
- components/o3-button/stories/buttons.scss
- components/o3-button/stories/buttons.stories.tsx
- components/o3-button/stories/sub-brand-in-brand.stories.tsx
- components/o3-button/whitelabel.css
update brand style importing for storybook
> chore: update brand style importing for storybook

- components/o-buttons/README.md
> chore: use consistent language in o-button accessibility readme.

- components/o-comments/src/scss/coral-talk-iframe/main.scss
We are going to change "Comments guidelines" text to a h3 element , and to keep the same aspect as before we need to reduce the space between h3 and text below
> fix: fix style specific element

- components/o-forms/README.md
- components/o-forms/demos/src/ft-live.mustache
- components/o-forms/main.scss
- components/o-forms/origami.json
- components/o-forms/src/scss/_checkbox.scss
- components/o-forms/src/scss/_radio-box.scss
- components/o-forms/src/scss/_radio-round.scss
- components/o-forms/src/scss/shared/_brand.scss
- components/o-forms/src/tsx/Form.tsx
- components/o-forms/src/tsx/RadioBtns.tsx
- components/o-forms/stories/boxRadioBtns.stories.tsx
- components/o-forms/stories/checkboxes.stories.tsx
- components/o-forms/stories/radioBtns.stories.tsx
Correctly apply the inverse / non-inverse focus state for themes, depending on contrast.
> feat: o-forms, fix focus state for professional-inverse [OR-312]

- .github/workflows/chromatic.yml
when changes are merged to main which may impact the storybook, including component changes
> backstage: selectively deploy o3 storybook to chromatic

- components/o3-button/main.css
- components/o3-button/src/tsx/button.tsx
- components/o3-button/stories/story-templates.tsx
- components/o3-web-token/README.md
Making some small changes to trigger the first release of o3-web-token and o3-button
> O3 initial relelase

- components/o3-button/package.json
- components/o3-web-token/package.json
- repo data is erroring because of missing origami.json files
- and includes build folder to be published to NPM
> fix: add build folder for o3-button and add origami.json as part of packages

- .github/workflows/release-please.yml
- components/o3-button/package.json
- components/o3-web-token/package.json
- Removes Percy from package JSON
> fix: udpate package json

- components/o3-button/package.json
- package-lock.json
Bump dependency version for o3 button on o3-web-token
> fix: update dep version for o3-web-token

- .github/labeler.yml
- .github/workflows/test.yml
- components/o-autocomplete/test/js/autocomplete.test.js
- components/o-banner/test/banner.test.js
- components/o-header/test/mega.test.js
- components/o-tabs/test/Tabs.test.js
- libraries/o-testing-library/README.md
- libraries/o-testing-library/index.js
- libraries/o-testing-library/main.js
- libraries/o-testing-library/package.json
- package-lock.json
- tools/test-javascript/web-test-runner.config.mjs
We had some issues with testing after installing new modules for o3 components. We tried to have a different approach to fix issues with the old component setup but this solution, compiling problematic modules for web-test-runner, seemed easiest so far and it seems like it resolves problems with testing.
> feat: release o-testing-library

- release-please-config.json
- scripts/regenerate-ci-config-files.js
We accidentally merge bad PR and now it's trying to publish minor changes for some components. Not to do this we are manually setting good PRs SHA.
> chore: update last release sha

- apps/o2-storybook-composition/stories/home.stories.mdx
> docs: add descriptions for each main heading in o2 storybook composition

- apps/astro-website/src/content/posts/2023-11-30-newsletter.md
Description is missing from newsletter causing deployments to fail. This fixes this.
> docs: include description

- apps/astro-website/README.md
> docs: add instructions on tagging newsletter

- apps/astro-website/src/content/posts/2023-11-30-newsletter.md
The November newsletter wasn't deploying to email for some reason. Adding a tag fixes this.
Documentation will be updated in a separate PR.
> docs: tag November newsletter

- components/o3-button/src/tsx/button.tsx
- package-lock.json
- package.json
We already have prettier installed, but it appears it runs optionally depending on local developer configuration.
This PR proposes an approach where prettier formats and writes files staged for commit before comitting happens, ensuring any changed files now follow our prettier rules.
> backstage: introduce prettier write pre-commit

- apps/for-everyone-website/src/content/docs/sustainable-views/components/buttons.mdx
more work needed to link to correct figma/storybook for a given brand in shared content
> chore: correct SV storybook link for buttons

- apps/for-everyone-website/package.json
- package-lock.json
> chore: depend on latest o3 components in for everyone site

- apps/astro-website/src/pages/emails/[slug].astro
This will not help emails sent in the past. Discussing with Martech to learn more about the scale of the problem, open an incident.
> chore: remove image from an S3 bucket the FT no longer controls

- apps/astro-website/src/content/posts/2024-01-24-sass-build-times.md
- apps/astro-website/src/layouts/DocLayout.astro
- apps/astro-website/src/layouts/Head.astro
focus more on steps we would like teams to take
> docs: remove sass-css monitoring post

- apps/astro-website/src/helpers/email-newsletter.js
Most of these changes are Prettier.
See line 103
> fix: ensure email images include an absolute path

- apps/astro-website/src/pages/storybook.astro
We have now moved all demos over
> docs: update storybook docs

- components/o-forms/stories/radioBtns.stories.tsx
> docs: correct radio buttons story title

- apps/o2-storybook/.storybook/main.ts
- components/o-viewport/stories/docs/jsdoc.md
- components/o-viewport/stories/jsdoc.stories.mdx
- components/o-viewport/stories/readme.stories.mdx
- libraries/o-autoinit/stories/readme.stories.mdx
Migrate Readme and jsdoc to populate storybook demos for `o-autoinit` and `o-viewport`
[OR-566](https://financialtimes.atlassian.net/browse/OR-566)
[OR-566]: https://financialtimes.atlassian.net/browse/OR-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: generate readme, jsdoc for o-autoinit and o-viewport

- release-please-config.json
- scripts/regenerate-ci-config-files.js
The commit contained changes for a lot of projects and tried to release a lot of unrelated stuff. Skipping.
> backstage: skip g-audio release

- apps/o3-storybook/.storybook/main.ts
- components/o-buttons/MIGRATION.md
- components/o3-button/README.md
- components/o3-button/package.json
- components/o3-button/stories/core/button.stories.tsx
> o-buttons to o3-buttons migration [OR-561]

- components/o-comments/src/scss/coral-talk-iframe/main.scss
Correct selector for notifications button fix
https://financialtimes.atlassian.net/browse/CI-2084
NA
> fix: ci-2084 comments notification button nesting fix

- components/o-cookie-message/README.md
(and, Prettier did its think 🙃 )
> docs: o-cookie-message README, update js import

- .gitignore
> backstage: ignore code editor specific files

- components/o-colors/MIGRATION.md
We need to provide a migration path for colour usecases and `oColorsMix`
> Add o-colors to o3-web-token migration guide [OR-563]

- components/o3-tooltip/README.md
Small readme changes to force a release of previous commits.
> fix: Support JSX for commonjs and node10 module resolution

- README.md
- apps/astro-website/src/pages/index.astro
- components/o-forms/README.md
- components/o-forms/src/scss/modifiers/_custom.scss
* Replaces links to Origami Registry with Storybook
* Updated copy to reflect the impending decommission of Registry.
*
> chore: replace Origami Registry links with Storybook.

- apps/astro-website/src/pages/decomission-notice.astro
Introduces a new astro page for the decomission of the Registry.
The Registry subdomain will be configured to redirect to this page once the decomission has happened.
> backstage: introduce Origami Registry decommission notice

- components/o-teaser/src/scss/elements/_default.scss
- components/o-teaser/src/scss/elements/_promoted.scss
increase teaser margin size for improved tapability
https://financialtimes.atlassian.net/browse/CON-2989
https://financialtimes.slack.com/archives/C04RUBL9G/p1699546073475049
> feat: increase teaser margin size for improved tapability

- components/o3-button/stories/pagination-template.tsx
- components/o3-button/stories/story-templates.tsx
fix: remove unused types and fix type paths
> fix: remove unused types and fix type paths

- components/o-autocomplete/README.md
> docs: remove id selector from o-autocomplete exampls

- apps/dictionary/tokens/$metadata.json
- apps/dictionary/tokens/$themes.json
- apps/dictionary/tokens/sustainable-views/use-case/color.json
- components/o3-foundation/src/css/tokens/sustainable-views/_variables.css
chore: added usecase colors for sustainable views
> chore: added usecase colors for sustainable views

- components/o3-button/README.md
> feat!: release v1 of o3-button

- .github/workflows/release-please.yml
- package-lock.json
- package.json
- scripts/lib/slack-announcer.js
- scripts/publish.js
This used to be powered by Origami Repo Data, which is now decommissioned. 
```
___
,-""   `.
,'  _   e )`-._
/  ,' `-._<.===-'  o-HONK!
/  /
/  ;
_          /   ;
(`._    _.-"" ""--..__,'    |
<_  `-""                     \
<`-                          :
(__   <__.                  ;
`-.   '-.__.      _.'    /
\      `-.__,-'    _,'
`._    ,    /__,-'
""._\__,'< <____
| |  `----.`.
| |        \ `.
; |___      \-``
\   --<
`.`.<
`-'
```
Example
```
node ./scripts/publish.js '{
"releases_created": "true",
"components/o-overlay--release_created": "true",
"components/o-overlay--id": "14[3](https://github.com/Financial-Times/origami/actions/runs/8047566508/job/21977073744#step:6:3)599668",
"components/o-overlay--name": "o-overlay: v[4](https://github.com/Financial-Times/origami/actions/runs/80 …
```
> backstage: Bring back Slack notifications for component releases [OR-584]

- components/o-header-services/src/scss/_functions.scss
- components/o-icons/src/scss/_mixins.scss
- components/o-share/main.scss
- components/o-social-follow/main.scss
Changed error message to remove syntax that's trying to create a hyperlink. It is incompatible with some terminals
> fix: tweak the `$system-code` error message to include a simple link

- components/o-autocomplete/package.json
- components/o-autocomplete/src/js/autocomplete.js
- package-lock.json
This PR updates the comment in `components/o-autocomplete/src/js/autocomplete.js` which explains why it uses a fork of alphagov/accessible-autocomplete.
Some of the details in the comment have since change so this PR revises it accordingly based on the following:
- This was fixed on 26 Jan 2024 by https://github.com/alphagov/accessible-autocomplete/pull/553
- It uses `null` instead of `undefined` but seems the net effect is the same
- This bug is still present
- > [May 24, 2021] Really appreciate your work, however at the moment we don't have capacity to deal with issues and pull requests on this repo unfortunately: https://github.com/alphagov/accessible-autocomplete/issues/430
- Activity on this repo seems to have picked up a fair amount since the start of this year so might be worth …
> chore: Update o-autocomplete comment

- apps/astro-website/src/components/header/Header.astro
- apps/astro-website/src/content/documentation/components/customisation.md
- apps/astro-website/src/content/documentation/tutorials/build-service.md
- apps/astro-website/src/content/documentation/tutorials/create-a-new-component-part-1.md
- apps/astro-website/src/content/documentation/tutorials/create-a-new-component-part-3.md
- apps/astro-website/src/content/documentation/tutorials/create-a-new-component-part-4.md
- apps/astro-website/src/content/documentation/tutorials/create-a-new-component-part-8.md
...and replace some remaining Registry links for Storybook.
> Remove registry banner

- apps/dictionary/tokens/internal/use-case/color.json
- apps/dictionary/tokens/whitelabel/use-case/color.json
- components/o3-foundation/src/css/tokens/internal/_variables.css
- components/o3-foundation/src/css/tokens/whitelabel/_variables.css
> fix: set values for link-inverse tokens

- components/o3-typography/package.json
- package-lock.json
> fix: peer dependency on correct foundation library

- components/o3-typography/src/css/brands/internal.css
- components/o3-typography/src/css/brands/professional.css
- components/o3-typography/src/css/brands/whitelabel.css
> fix: fix broken css imports

- components/o3-typography/package.json
> fix: use correct export approach

- .github/workflows/chromatic.yml
- .github/workflows/o2-chromatic.yml
- .github/workflows/o2-composition-chromatic.yml
I'm finding it hard to see what's running under the Actions tab with a shared name.
> chore: distinguish Github Actions and jobs

- apps/for-everyone-website/src/components/TypeScale.astro
- apps/for-everyone-website/src/content/docs/guides/typography.mdx
List both type scale on the for everyone website
> docs: list all type scales

- CONTRIBUTING.md
Add more information on making a release.
> docs: Update contribution guide 

- components/o-multi-select/src/js/multi-select-options.js
Jira [ticket](https://financialtimes.atlassian.net/browse/SP-3623)
> Option label is now trimmed of spaces

- package-lock.json
> backstage: regenerate package-lock.json

- apps/o3-storybook/.storybook/main.ts
> docs: enable autodocs on o3-storybook

- components/o-layout/README.md
- components/o-layout/main.scss
Helpful if font faces have already been output, e.g. using `o-fonts` directly or custom fonts.
> feat: Allow font output to be turned off for o-layout

- apps/for-everyone-website/README.md
- apps/for-everyone-website/package.json
- apps/for-everyone-website/public/styles/email.css
- apps/for-everyone-website/src/helpers/email-newsletter.js
- apps/for-everyone-website/src/pages/emails/[slug].astro
The script is untested as I have had issues trying to access origami.ft.com from my local machine.
> backstage: migrate send newsletter scripts

- apps/for-everyone-website/package.json
- package-lock.json
- package.json
- patches/@astrojs+starlight+0.23.4.patch
This seems to apply now with a fresh install from root
> chore: Move patch-package to root

- apps/for-everyone-website/remove-branded-headings.mjs
Handle table of contents with list items that have no links, just in case
> chore: Update heading link removal script

- components/o3-editorial-typography/README.md
> chore: release 1.1.0

- components/o3-foundation/README.md
> chore: release 1.2.0

- apps/for-everyone-website/src/content/docs/about/measuring-success.md
Remove reference to measures that would be nice, but we're not actively monitoring over time.
> docs: Update measures page to reflect reality.

- package-lock.json
- tools/o3-chrome-extension/README.md
- tools/o3-chrome-extension/package.json
- tools/o3-chrome-extension/public/manifest.json
Add documentation around updating the extension.
> docs: add guidlines on how to update the extension

- apps/for-everyone-website/src/content/docs/guides/typography.mdx
> docs: Fix Georgia copy

- components/o-table/package.json
- package-lock.json
> chore: upgrade ftdomdelegate to v5 in o-table

- components/o-header/MIGRATION.md
- components/o-header/src/scss/_brand.scss
- components/o-header/src/scss/_mixins.scss
- components/o-header/src/scss/_variables.scss
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_search.scss
- components/o-header/src/scss/features/_top.scss
- components/o-header/src/tsx/Props.ts
- components/o-header/src/tsx/components/ask-ft-button.tsx
- components/o-header/src/tsx/drawer.tsx
- components/o-header/src/tsx/header-default.tsx
- components/o-header/src/tsx/header.tsx
- components/o-header/src/tsx/search.tsx
- components/o-header/src/tsx/sticky.tsx
- components/o-header/src/tsx/top.tsx
- components/o-header/stories/arg-types.ts
- components/o-header/stories/header.stories.tsx
> release staged o-header changes

- apps/o3-storybook/readme.md
Adds some basic requirements of stories to help when reviewing PRs containing story changes/additions.
> docs: add story requirements

- release-please-config.json
- scripts/regenerate-ci-config-files.js
> chore: make release please ignore unreleased commits

- components/o3-button/main.css
- components/o3-editorial-typography/README.md
- components/o3-tooltip/main.css
> Release new major versions

- components/o3-button/README.md
- components/o3-editorial-typography/README.md
- components/o3-tooltip/README.md
Stealth PR to release changes on main that previously were not released.
> feat!: use metric tokens for font-size and line height

- apps/for-everyone-website/src/content/docs/components/buttons.mdx
- package-lock.json
> fix: fix issues with social sign on preview not displaying figma links

- apps/dictionary/tokens/$themes.json
- apps/dictionary/tokens/whitelabel/components/o3-form.json
- apps/dictionary/tokens/whitelabel/components/o3-form/use-case.json
> chore: tidy up tokens for o3-form

- libraries/o-tracking/src/javascript/tracking.js
Correctly update the reported o-tracking version
> fix: version bump

- components/o-comments/main.scss
- components/o-comments/package.json
- components/o-comments/src/scss/_mixins.scss
- components/o-comments/src/scss/coral-talk-iframe/main.scss
- components/o-forms/README.md
- components/o-forms/package.json
- components/o-forms/src/scss/_file-input.scss
- components/o-forms/src/scss/main.scss
- components/o-forms/src/scss/modifiers/_inverse.scss
- components/o-forms/stories/forms.scss
- components/o-header/main.scss
- components/o-header/package.json
- components/o-header/src/scss/_variables.scss
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_search.scss
- components/o-header/src/scss/features/_transparent.scss
- components/o-private-foundation/main.scss
- components/o-private-foundation/src/scss/_brand.scss
- components/o-private-foundation/src/scss/o-buttons/main.scss
- components/o-table/src/scss/_responsive-overflow.scss
- components/o-tabs/README.md
- components/o-tabs/main.scss
- components/o-tabs/package.json
- components/o-tabs/src/scss/_buttontabs.scss
- components/o-tabs/stories/tabs.scss
I needed to make some changes to other packages to support this. See commit messages.
> Remove o-buttons from o-tabs, o-header, o-forms, o-comments

- components/o-overlay/test/specs/o-overlay.test.js
This test is failing on main despite no recent changes. o-overlay is in maintenance mode with no future development plans. Therefore, we will ignore the failing test.
> chore: Delete o-overlay test

- .github/CODEOWNERS
This PR updates the CODEOWNERS file to reflect its new ownership.
[LIF-2: Admin for setting up Lifecycle team's resources](https://financialtimes.atlassian.net/jira/software/c/projects/LIF/boards/2009/?selectedIssue=LIF-2)
N/A
> chore: Update CODEOWNERS to @Financial-Times/cp-customer-lifecycle

- components/o3-editorial-typography/details.css
- components/o3-editorial-typography/drop-cap.css
- components/o3-editorial-typography/main.css
- components/o3-editorial-typography/src/css/brands/whitelabel.css
- components/o3-editorial-typography/stories/core/body.stories.tsx
- components/o3-editorial-typography/stories/core/professional/body.stories.tsx
- components/o3-editorial-typography/stories/sustainable-views/body.stories.tsx
- Topic tag 
- Standfirst
- Drop cap
> Apply more use-case tokens to o3 components. 

- components/o-quote/README.md
> docs: add deprecation notice

- components/o-forms/stories/forms.scss
- components/o-forms/stories/textBox.stories.tsx
- components/o-private-foundation/src/scss/o-buttons/main.scss
- components/o3-button/main.css
[This aligns with the increased type size of forms.](https://financialtimes.slack.com/archives/G03ACR1MJ/p1737547202189199)
> Increase type size of standard button

- components/o-private-foundation/package.json
- package-lock.json
> fix: Ensure o-private-foundation depends on the latest o-brand

- components/o-header/package.json
- package-lock.json
> fix: bump o-private-foundation version

- components/o-header/package.json
- package-lock.json
> fix: bump o-private-foundation

- apps/for-everyone-website/src/content/docs/contribution/brands.mdx
- apps/for-everyone-website/src/content/docs/contribution/index.md
- apps/for-everyone-website/src/content/docs/contribution/tone-and-language.md
This is a starting point and covers the broad steps. There may be missing steps. We can certainly add more detail. This will come in future PRs and end with following the steps to test them out.
> docs: Contribution, steps to add a new brand.

- apps/for-everyone-website/src/content/docs/guides/spacing.mdx
- apps/for-everyone-website/src/content/docs/o2-components/index.md
- apps/for-everyone-website/src/content/docs/o2-components/technical-guide/origami-build-service.md
- apps/for-everyone-website/src/content/docs/patterns/pagination.mdx
- components/o-forms/README.md
- components/o-forms/src/scss/modifiers/_custom.scss
- components/o-icons/README.md
- components/o3-foundation/README.md
> docs: update storybook links to new structure

- apps/for-everyone-website/src/content/docs/about/faq.md
- apps/for-everyone-website/src/content/docs/getting-started/design-guide.md
- apps/for-everyone-website/src/content/docs/getting-started/index.md
- apps/for-everyone-website/src/content/docs/getting-started/technical-guide.mdx
- apps/for-everyone-website/src/content/docs/getting-started/technical-guide/package-manager-npm.md
- apps/for-everyone-website/src/content/docs/index.mdx
> Mobbing qa changes beta site

- components/o-typography/MIGRATION.md
> docs: ensure oTypographySans scale migration steps are correct

- .github/pull_request_template.md
Added in the URLs for JIRA tickets and Figma. If you know the ticket number you can just fill in the blanks. The same goes for Figma, copy and paste link and edit the link name. Would save maybe 0.1 seconds every PR but quality of life is greatly improved.
> chore: improve pull request template

- components/o3-button/src/css/brands/core.css
- components/o3-button/src/css/brands/professional.css
For @notlee and for `release-please` to be entirely happy again!
> feat: o3-button: add neutral theme for primary/ghost

- components/o3-button/src/css/brands/core.css
- components/o3-button/src/css/brands/professional.css
Please release the new version of `o3-button` and nothing else 🙏🏻
> feat: improve grammar on comments for core/professional

- apps/for-everyone-website/src/content/docs/guides/grid.mdx
> docs: fix  failing deployment due to website `grid.mdx` file formatting issue

- apps/for-everyone-website/src/components/editorial-typography/Display.astro
- apps/for-everyone-website/src/content/docs/guides/grid.mdx
- apps/for-everyone-website/src/content/docs/guides/typography.mdx
> docs: fix website text formatting and typos

- components/o-teaser/src/scss/themes/_top-stories.scss
> fix: Correct top story font size

- components/o3-foundation/stories/core/proffesional/color-palette.stories.tsx
- components/o3-foundation/stories/core/proffesional/grid.stories.tsx
- components/o3-foundation/stories/core/proffesional/icons.stories.tsx
- components/o3-foundation/stories/core/proffesional/spacing.stories.tsx
- components/o3-foundation/stories/story-templates.tsx
Do horrible things for good reasons. We want to revisit how we handle the pro sub-brand to avoid issues like this
> docs: Fix o3 SB build

- apps/website/remove-branded-headings.mjs
> docs: ensure branded headings are removed

- tools/o3-chrome-extension/README.md
- tools/o3-chrome-extension/package.json
- tools/o3-chrome-extension/public/manifest.json
- tools/o3-chrome-extension/src/styles/grid.css
- tools/o3-chrome-extension/src/styles/popup.css
| [OR-1541](https://financialtimes.atlassian.net/browse/OR-1541) | N/A |
> ⚠️ Note: I tried out GitHub CoPilot to do a summary. It worked out pretty well I think 😂 
This pull request introduces updates to the `o3-chrome-extension` project, focusing on improving documentation, updating dependencies, enhancing styles, and preparing the extension for publishing. The most significant changes include revisions to the README for clarity and completeness, updates to versioning and dependencies, and adjustments …
> [OR-1541] Upgrade o3-chrome-extension to o3-grid v2

- libraries/o3-figma-sb-links/src/figma-links.json
- libraries/o3-figma-sb-links/src/links.json
- libraries/o3-figma-sb-links/src/sb-links.json
> backstage: generate o3 form checkbox description story links

- components/o-header-services/src/scss/_functions.scss
> feat: use image service v3 in o-header-services
