- .github/CONTRIBUTING.md
I think this makes more sense considering the names of
the other columns. I think the flow makes more sense:
```diff
- Proposed  >  In Progress  >  Accepted
-                           >  Not Accepted
+ Proposed  >  Under Consideration  >  Accepted
+                                   >  Not Accepted
```
I've updated all of the labels and the actual column
names already. Thanks @wheresrhys for the suggestion.
> Rename "In Progress" to "Under Consideration"

- .github/CONTRIBUTING.md
- proposals/accepted/0000-template.md
- proposals/accepted/0060-proposals-in-repo.md
rendered proposal: https://github.com/Financial-Times/origami/blob/13fd5401cc527df9e8a2e35ed5730163cd798ed8/proposals/accepted/0060-proposals-in-repo.md
i've made it 0060 as that was the previous issue's id #60, and that way we can migrate old issues to this format like this
> Proposals in the repo

- proposals/accepted/0000-move-description-and-keywords-to-package-json.md
👋 When working on the proposal to have origami components only on npm, [chee suggested](https://financialtimes.slack.com/archives/CSW6B2VAN/p1602497687031500) that we could move these fields from the origami.json manifest to the package.json manifest as then they could be used by npm clients such as the public npm registry. We missed adding the suggestion into the original proposal, so I am writing it up as a separate proposal now
👉 [View the rendered proposal here](https://github.com/Financial-Times/origami/blob/manifests/proposals/accepted/0000-move-description-and-keywords-to-package-json.md).
👇 leave comments and any more examples below
> Add proposal to move `description` and `keywords` fields from origami.json into package.json

- proposals/accepted/0000-delete-origamiCategory-manifest-field.md
👋 When working on the proposal to have origami components only on npm, [chee suggested](https://financialtimes.slack.com/archives/CSW6B2VAN/p1602497687031500) that we could remove this field from the origami.json manifest as it not being used by anything. 
👉 [View the rendered proposal here](https://github.com/Financial-Times/origami/blob/origamiCategory/proposals/accepted/0000-delete-origamiCategory-manifest-field.md).
👇 leave comments and any more examples below
> Add proposal to remove origamiCategory from origami.json manifest

- proposals/accepted/0000-remove-silent-mode.md
👉 [view rendered proposal](https://github.com/Financial-Times/origami/blob/remove-silent-mode-variable/proposals/accepted/0000-remove-silent-mode.md)
> Remove silent mode variable for spec v2 components

- .gitignore
We only want a root package-lock.json, it knows about all the packages
> chore: ignore package-lock

- .github/workflows/release-please.yml
I read https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages and I think this might need to be set in order for the .npmrc file to then be able to run npm publish
> chore: explicitly configure the npmjs used when publishing

- components/o-layout/test/helpers/fixtures.js
- package-lock.json
This will hopefully mean that the headless browser never selects the h2
> chore: Add content to fixture between h1 and h2

- README.md
I think we should also add a readme to all of the top-level directories
so we can give people a little more info when they browse in.
for instance: document the scripts in scripts/readme.md
> add a small amount of documentation to the README

- components/o-date/.prettierrc.toml
- components/o-date/demos/src/declarative.js
- components/o-date/demos/src/declarative.mustache
So that percy doesn't show a different date every time
I'll change this to a `docs: ` commit and do a force push after percy has run. This doesn't need a release.
> add a specific time for the demo date that prints the whole date

- .github/workflows/build-websites.yml
the website's images are stored in LFS to prevent repo slowness
> checkout with lfs when building websites

- components/o-normalise/src/scss/_mixins.scss
Originally for [this ticket](https://financialtimes.atlassian.net/browse/ADSDEV-899), there were several ways to potentially resolve this.
This is possibly the best as all as the `oNormaliseVisuallyHidden` component is already invisible by a `clip: rect(0,0,0)`, so increasing its footprint to 2px should not affect anything visually... but should help with accessibility!
Let me know if there are any questions.
> [ADSDEV-899] - updated width and height to 2px to better serve users with voice activation software

- .github/labeler.yml
- .github/workflows/test-tools-validate-component-demo-html.yml
- components/o-autocomplete/README.md
- components/o-autocomplete/demos/src/dynamic-complex/dynamic-complex.mustache
- components/o-autocomplete/demos/src/dynamic-delayed/dynamic-delayed.mustache
- components/o-autocomplete/demos/src/dynamic/dynamic.mustache
- components/o-autocomplete/demos/src/static/static.mustache
- components/o-autocomplete/package.json
- components/o-autocomplete/test/js/helpers/fixtures.js
- components/o-colors/demos/src/color-mixer/color-mixer.js
- components/o-colors/demos/src/color-mixer/color-mixer.scss
- components/o-colors/demos/src/color-mixer/index.mustache
- components/o-table/README.md
- components/o-table/demos/src/base.mustache
- components/o-table/demos/src/basic.mustache
- components/o-table/demos/src/pa11y.mustache
- package-lock.json
- presets/remark-preset-lint-origami-component/test/invalid/invalid-missing-general-usage/README.md
- presets/remark-preset-lint-origami-component/test/invalid/kitchen-sink/README.md
- presets/remark-preset-lint-origami-component/test/valid/financial-times-namespace/README.md
- presets/remark-preset-lint-origami-component/test/valid/table-of-contents-heading/README.md
- presets/remark-preset-lint-origami-component/test/valid/table-of-contents-no-heading/README.md
- scripts/component/test.bash
- tools/validate-component-demo-html/README.md
- tools/validate-component-demo-html/index.js
- tools/validate-component-demo-html/package.json
I'm using [html-validate](https://www.npmjs.com/package/html-validate) with the `html-validate:standard` preset.
However I've overridden the preset so `buttons` don't require a `type` and `th` elements don't require a `scope`.
I don't think either of these are actually required and the browser default is fine.
>Enables rules related to validating according to the WHATWG HTML standard (Living Standard).
>Use this preset if you want validation similar to the Nu Html Checker and similar tools.
Here's where the magic happens:
https://github.com/Financial-Times/origami/compare/validate-component-demo-html?expand=1#diff-51a745927fcfcc4176f0a09906a4f9bdcf155b460c7960bc25d06349d83cfe70R1
See commits for more details.
Closes: https://github.com/Financial-Times/origami/issues/328
> Validate component demo html

- presets/remark-preset-lint-origami-component/rules/readme-has-name.js
- scripts/component/lint.bash
grab the readme-relative package.json rather than the cwd-relative one
> fix remark-lint-origami-component readme-has-name check

- README.md
- components/o-layout/test/layout.test.js
- package-lock.json
- presets/eslint-config-origami-component/config.js
- presets/eslint-config-origami-component/package.json
The changes applied at to increase the viewport to one we know will work and to use `waitUntil` (https://open-wc.org/docs/testing/helpers/#waituntil) to periodically poll the dom until the aria-current attribute has been updated
This should resolve https://github.com/Financial-Times/origami/issues/329
> backstage: rewrite the o-layout test to be less flakey

- scripts/percy.js
Previously Percy would move all the demos from `demos/local` to `demos/percy` and rename the demos to include the brand in their filename.
In a [previous patch](https://github.com/Financial-Times/origami/pull/450), we stopped doing the moving and renaming of demos but we did not update the percy command to run from `demos/local`
> Make percy snapshot from the demos/local folder which is where the demos live

- tools/origami-bower-safe-version-supervisor/package.json
This is required the first time a namespaced package is published - the default access for namespace packages is private.
If this is not set in package.json or the npm CLI then this error is shown during publishing:
>npm ERR! code E402
>npm ERR! 402 Payment Required - PUT registry.npmjs.org/@financial-times%2forigami-bower-safe-version-supervisor - You must sign up for private packages
> fix: explicitly state package should be published publically

- components/o-stepped-progress/MIGRATION.md
- components/o-stepped-progress/README.md
- components/o-stepped-progress/src/scss/_mixins.scss
We currently have two hacks, one for IE9 and one that overrides the hack for
IE10 and IE11. We don't support IE9 so instead of doing two things we can do
none, which is the number of things I prefer to do.
I'm releasing this as a breaking change, but really I don't think it is because
I don't think we ever told anyone we support IE9 and this component was made
after we no longer supported IE9. What ya gonna do, though? call the cops?
live laugh love
stay humble
🧱
> fix!: Drop IE9 support in o-stepped-progress

- libraries/sass-mq/package.json
This library was not publishing the index.scss file. This pr makes it so all files not in the package.json.ignore are published, including index.scss
> fix: remove the files attribute so we publish the correct files

- components/o-banner/demos/src/custom.mustache
vscode complains about it -- should we replace it with a word-break-opportunity element? `<wbr>`
vscode says this:
>The file 'custom.mustache' contains one or more unusual line terminator characters, like Line Separator (LS) or Paragraph Separator (PS).
>It is recommended to remove them from the file. This can be configured via `editor.unusualLineTerminators`.
> o-banner: remove unused line-separator in demo

- components/o-forms/demos/src/interactive.mustache
- components/o-forms/demos/src/inverse-form-whitelabel.mustache
- components/o-forms/demos/src/inverse-form.mustache
Some of the demos contain inputs which have no IDs. If an input has no ID and the input has an error state - then when the error summary is shown it will not be able to link to the input, which violates the WCAG 2.4.1 Bypass Blocks (Level A) rule.
I think it's best to remove these inputs from the demos as we should not be demoing how to create inaccessible forms/inputs
Resolves #524
> o-forms remove demo inputs which have no ID

- components/o-forms/demos/src/interactive.mustache
- components/o-forms/demos/src/inverse-form-whitelabel.mustache
- components/o-forms/demos/src/inverse-form.mustache
- components/o-forms/test/helpers/fixtures.js
The ID's for the radio inputs were previously named date-group-title2 when they had nothing to do with dates
> o-forms: rename demo date and radio ID's to have more relatable names

- .github/workflows/build-websites.yml
A new Storybook Story is throwing an unhelpful error in production.
Hmm. Building locally works with:
`NODE_ENV=production npm run build-storybook`
`npx serve origami.ft.com/storybook`
I see the production release seems to request more js files on load than my local build, and that
the build dir includes a bunch of older files from previous builds. They are hashed so I don't
think this is a problem but I would expect previous build assets to be removed as the
github-pages-deploy-action `clean` option is `true` by default.
https://github.com/Financial-Times/origami/tree/cc2710bc80432128b1cda8d3dd009936ed625131/storybook
https://github.com/JamesIves/github-pages-deploy-action#optional-choices
I don't have time to look into the problem further right now,
so let's bump the version and hope …
> backstage: bump github-pages-deploy-action used to release the site

- tools/demo-build/index.js
- tools/origami-tools-helpers/construct-polyfill-url.js
- tools/origami-tools-helpers/index.js
this enables us to test demos locally in older browsers such as ie11
this is relying on the origami.json.browserFeatures array which I know we plan to remove. When we do remove it, we will need to find a replacement solution for running local demos in older browsers
this code is a rewrite of what was in origami-build-tools (https://github.com/Financial-Times/origami-build-tools/blob/e7fe4046aca39bd4823f109fcd45cb4b33cd7ce2/lib/helpers/construct-polyfill-url.js) to make it work in a monorepo
> add polyfill.io urls to local demos

- components/o-header/src/js/mega.js
- components/o-header/test/mega.test.js
this is required to meet WCAG 1.4.13 Content on Hover or Focus (Level AA)
this resolves https://github.com/Financial-Times/origami/issues/549
> o-header: add the ability to close any open mega-menus by pressing the escape key

- components/o-tabs/MIGRATION.md
- components/o-tabs/README.md
- components/o-tabs/demos/src/base-style.mustache
- components/o-tabs/demos/src/buttontabs-big.mustache
- components/o-tabs/demos/src/buttontabs-inverse.mustache
- components/o-tabs/demos/src/buttontabs-primary.mustache
- components/o-tabs/demos/src/buttontabs.mustache
- components/o-tabs/demos/src/pa11y.mustache
- components/o-tabs/src/js/Tabs.js
- components/o-tabs/test/Tabs.test.js
- components/o-tabs/test/helpers/fixtures.js
- components/o-tabs/test/origami.test.js
This is an o-tabs implementation of [WAI-ARIA tab-panels](https://www.w3.org/TR/wai-aria-practices/#tabpanel)
Resolves #559 
The changes in this component include:
- added keyboard support for moving between tabs using arrow keys
- when navigating the tab-list or selecting a tab, keep focus within the tab-list and do not move focus to the shown tab-panel
- add aria-controls relationships between tabs and their associated tab-panel
- added support to activate a tab by pressing the space-bar
> o-tabs: implement all the required features for a tab component which implements the wai-aria tabs design pattern

- apps/storybook/config/main.js
this is the panel we usually want to use i think
> register essentials before a11y so the controls panel is default panel

- components/o-grid/src/scss/_mixins.scss
`oGridAddLayout` used to error when adding a new larger layout.
Since that has been fixed we discovered it also sets the max
grid width to the new larger layout. A user doesn't necessarily
want this, for example when the new breakpoint is used to
target background imagery for large screens.
> fix: o-grid, retain existing max grid width when adding larger layout

- components/o-banner/stories/banner.stories.tsx
- components/o-buttons/stories/button.stories.tsx
- components/o-cookie-message/stories/cookie-message.stories.tsx
- components/o-stepped-progress/stories/stepped-progress.stories.tsx
i think this is probably more clear, and then later we can add
a nice Guidance directory, maybe a Design directory and an Accessibility directory?
whatever the future holds.
before:
looks like this now:
> move component stories into a subdir and rename to component name

- components/o-banner/src/js/banner.js
- components/o-banner/test/banner.test.js
If an element has both a title attribute and an aria-label attribute, then both will be read out by screen-readers
This change removes the aria-label attribute and keeps the title attribute.
This resolves issue https://github.com/Financial-Times/origami/issues/554
> o-banner: do not repeat the description for the banner close button

- components/o-cookie-message/README.md
- components/o-cookie-message/src/js/cookie-message.js
specialist titles used to need it to be on /preferences/cookies, but will be
updating their pages to /preferences/manage-cookies. let's let them
set it.
this code could be less algorithmic. it appears flexible, but is not. it's
tied hard to the server and routing. i feel like maybe the component
should live alongside the server lib it's associated with, rather than
in origami.
> Allow configuring the path to the manage cookies page

- components/o-header/src/scss/features/_drawer.scss
previously only the top line of the focus ring was being shown
resolves https://github.com/Financial-Times/origami/issues/548
Without this change applied:
With this change applied:
> fix: show the entire focus ring for links within the drawer

- components/o-visual-effects/README.md
- components/o-visual-effects/main.scss
- components/o-visual-effects/src/scss/_shadows.scss
- components/o-visual-effects/stories/shadows-demo.tsx
- components/o-visual-effects/stories/shadows.stories.tsx
- components/o-visual-effects/stories/transition-demo.tsx
- components/o-visual-effects/stories/transitions.stories.tsx
- components/o-visual-effects/stories/visual-effects.scss
This one is interesting as demo CSS and markup is required. Although we prefer to 
avoid demo CSS and allow full demo markup to be copy/paster, I think this component 
Story belongs to visualise what the component provides – i.e. it's unlike contrast checking
tools which we currently have in o-colors and would like not to port to a Story under the 
o-colors component.
To make the HTML tab useful for build service users I've used the CSS custom properties
o-visual-effects outputs inline.
> Add o-visual-effects Story

- components/o-table/src/scss/_base.scss
- components/o-table/src/scss/_responsive-overflow.scss
fix: o-table filter when a second filter or more is applied
This commit sets filtered table rows to `display: none`, to remove
filtered row content from tabindex.
https://github.com/Financial-Times/origami/commit/e9e7a173581c9a58fc04f91f5c71bb32c0e905dc
However o-table requires that rows are rendered to figure out
what height to set on the table:
https://github.com/Financial-Times/origami/blob/f49145eab4acaed27d8268138082e3480af3f02f/components/o-table/src/js/Tables/BaseTable.js#L248
This means setting `display: none` broke table sorting visually.
Filtered rows already apply `visibility: hidden`:
https://github.com/Financial-Times/origami/blob/7a0971d7bb70b25b9f6484f0a4e982a5f27b18e5/components/o-table/src/scss/_base.scss#L74
Which means no child receives focus (according to mdn and …
> fix: o-table filter when a second filter or more is applied

- libraries/o-tracking/README.md
The FT moved from Chartio to Looker as the place to view our tracking data, this pull-request updates our documentation to use the new links for looker
> docs: update documentation on where and how to view the data sent from o-tracking

- apps/website/_posts/2021-07-01-origami-on-npm-and-how-to-migrate.md
Customer Products are first moving to npm without bumping
component version numbers, i.e. moving to the beta npm releases.
This is so they can release packages with both bower and npm
support to help the rollout. This has caused confusion because
it means they need to add `node_modules/@financial-times` to their
compiler's `includePath` configuration, it is not an option anymore.
The guide has been updated the cover that case. It has also been
updated to require Sass imports include the `@financial-times`
namespace, rather than rely on the compiler's `includePath`
configuration. This is because a project which does that forces
all its depndents to also.
> backstage: update origami via bower migration guide

- components/o-forms/src/scss/_checkbox.scss
closes: https://github.com/Financial-Times/origami/issues/668
> fix: checkboxes with long labels (split with multiple "label" span tags)

- libraries/o-tracking/README.md
- libraries/o-tracking/src/javascript/core/send.js
- libraries/o-tracking/test/core/send.test.js
By default o-tracking uses the browser Beacon API to send events to Spoor and the Beacon API only works when the device is online and o-tracking can not queue those events.
If wanting to queue events (to retry them if they failed to send) and/or wanting to record events when offline, set `queue` to `true` during the intialisation of `o-tracking` like so:
```js
import oTracking from '@financial-times/o-tracking';
const config = {
queue: true, // Make sure o-tracking stores the events on a local queue (this means o-tracking can work when the device is offline)
...
};
oTracking.init(config);
```
> feat: add ability to force o-tracking to use a queue

- components/o-header/demos/src/deprecated-markup.mustache
- components/o-header/demos/src/grid-demo.mustache
- components/o-header/demos/src/header.mustache
- components/o-header/demos/src/pa11y.mustache
- components/o-header/demos/src/simple-header.mustache
- components/o-header/demos/src/sticky-header.mustache
- components/o-header/demos/src/subbrand.mustache
- components/o-header/main.scss
- components/o-header/src/scss/_variables.scss
- components/o-header/src/scss/features/_anon.scss
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_nav.scss
- components/o-header/src/scss/features/_simple.scss
- components/o-header/src/scss/features/_top.scss
- components/o-header/src/scss/features/_transparent.scss
- package-lock.json
Markup changes here are non-breaking of previous markup.
Updates will be rolled out across ft.com via pagekit
Ticket: https://financialtimes.atlassian.net/browse/ACQ-1535
Closes: https://github.com/Financial-Times/origami/issues/688
> feat: update o-header with new subs button for annon readers

- components/o-header/demos/src/deprecated-markup.mustache
- components/o-header/demos/src/grid-demo.mustache
- components/o-header/demos/src/header.mustache
- components/o-header/demos/src/pa11y.mustache
- components/o-header/demos/src/simple-header.mustache
- components/o-header/demos/src/sticky-header.mustache
- components/o-header/demos/src/subbrand.mustache
- components/o-header/main.scss
- components/o-header/src/scss/_variables.scss
- components/o-header/src/scss/features/_anon.scss
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_nav.scss
- components/o-header/src/scss/features/_simple.scss
- components/o-header/src/scss/features/_top.scss
- components/o-header/src/scss/features/_transparent.scss
- package-lock.json
Suppports work to move the subscribe button to the sticky nav
for users who are logged in but not subscribed:
https://github.com/Financial-Times/dotcom-page-kit/pull/939
This state is not reflected in our demos. When we recreate
o-header demos in Storybook and provide JSX templates that
should be improved:
https://github.com/Financial-Times/origami/issues/522
> fix: o-header, handle nav icon spacing within `o-header__nav-item`

- components/o-header/demos/src/header-logo-only.mustache
- components/o-header/origami.json
- components/o-header/src/scss/features/_top.scss
this pattern is used on login/signup pages for a full size logo
> fix: center ft logo in o-header when right/left columns are missing

- components/o-toggle/main.js
At present, o-toggle is used in both o-header and o-footer.
I want to be able to SSR headers and footers, because there's not much point in SSR if you need a client-side effect to render the header and footer (resulting in large CLS, part of the point of SSR being to avoid). However, because of the Origami practise of accessing `document` as a module-importing side-effect, this is utterly impossible at present and causes e.g. NextJS to throw `ReferenceError: document is not defined`
If Origami is going to continue to follow its idiom of adding event listeners as a side effect on module import, could you please at least existence check for `document` before accessing it? This would solve like 90% of my problems.
> Checks for document before adding o.DOMContentLoaded event listener in o-toggle

- components/o-comments/MIGRATION.md
- components/o-comments/README.md
- components/o-comments/main.scss
- components/o-comments/src/js/stream.js
- components/o-comments/src/scss/_mixins.scss
- components/o-comments/src/scss/coral-talk-iframe/main.scss
o-comments relied on v2 of the Build Service to build `src/scss/coral-talk-iframe.scss` for the Coral Talk iframe, which would break when we drop Bower support.
https://github.com/Financial-Times/origami/tree/o-comments-v8.3.3/components/o-comments#styling-of-coral-talk-iframe
There’s no direct migration path to Build Service v3 in this case as it’s no longer possible to use the build service to bundle arbitrary sass files in the component’s src.
Instead output the coral talk iframe css as part of `main.scss` and rely on [Coral's containerClassName option](https://docs.coralproject.net/cms) to scope CSS to the iframe. Provide an option in the Sass interface to not output the styles intended for the Coral iframe, to reduce final project css bundle sizes.
Pros:
- All comment CSS co-located …
> feat!: Remove o-comments reliance on Build Service v2

- components/o-date/src/js/date.js
- components/o-date/src/tsx/date.tsx
- components/o-date/stories/date.stories.tsx
- package-lock.json
The original o-date demo is unusual in that multiple variations are included in a single demo, with different formatting settings included in one chunk of HTML. There are demos split out into ones written in declarative and imperative styles, though the imperative demos are already hidden so I haven't ported them over. I've instead split each line of the declarative demo into its own story so that their arguments can be fiddled with individually.
o-date also has support for 'copy options', where you can intersperse computed timestamps with some custom copy. This is done via inserting `span`s with some identifying attributes (as long as optionally setting custom formatting.) I can think of a few ways we could make this fit more ergonomically with the new JSX templates (converting string …
> Add stories for o-date demos

- .github/workflows/release-please.yml
- scripts/publish.js
The release-please Github Action would fail to publish components if the output
from release please contained a single quote, e.g. from a commit message.
To avoid this pass release please output via an enviroment variable.
Example of issue:
```
node ./scripts/publish.js '{
node ./scripts/publish.js '{
"releases_created": "true",
"components/o-date--release_created": "true",
"components/o-date--major": "5",
"components/o-date--minor": "3",
"components/o-date--patch": "0",
"components/o-date--sha": "8ef3512aaf867b3bc6b7c60b57e1557fc23e27d0",
"components/o-date--version": "5.3.0",
"components/o-date--pr": "745",
"components/o-date--html_url": "https://github.com/Financial-Times/origami/releases/tag/o-date-v5.3.0",
"components/o-date--name": "@financial-times/o-date o-date-v5.3.0", …
```
> backstage: handle single quotes in commit messages on release

- apps/storybook/config/main.js
- tools/origami-tools-helpers/files.js
I can’t build storybook for the internal brand due to an unrelated sass error `ORIGAMI_STORYBOOK_BRAND=internal npm run storybook`
– it tries to build `ft-concept-button` which doesn’t support the internal brand, and uses colours not supported by the internal
brand’s colour palette.
This commit updates Storybook config to check a component supports the current brand before building its stories. Currently this
does not support brand specific stories within a component, which we may want to support in the future.
To inspect a component's supported brands I chose to copy helper functions from the tools directory rather than create
some shared dependency between packages (tools and storybook).
> backstage: Storybook, fix internal brand build.

- components/o-tooltip/src/js/tooltip.js
- components/o-tooltip/test/Tooltip.test.js
- components/o-tooltip/test/helpers/fixtures.js
>A previous change made it so the close button doesn’t show if a tooltip is shown on hover or focus, but does show on click. It accidentally made it so if a tooltip is open by default on page load there is no close button, when there should be.
Relates to the following PR:
https://github.com/Financial-Times/origami/pull/419
> fix: o-tooltip show close button when opened on construction

- components/o-fonts/README.md
- components/o-fonts/src/scss/_mixins.scss
- components/o-fonts/src/scss/_variables.scss
The latest o-fonts major updated `$o-fonts-path` to point to
v3 of the Origami Build Service. This required setting font file
names in a query parameter, rather than sending a request for a
file explicity.
`https://www.ft.com/__origami/service/build/v3/font?version=1.12&font_name=MetricWeb-Regular&font_format=woff2&system_code=origami`
vs.
`https://www.ft.com/__origami/service/build/v2/files/o-fonts-assets@1.7.0/MetricWeb-Regular.woff`
This meant users could no longer set `$o-fonts-path` to self host fonts. 
This is something Financial-Times/ft-app does to support offline fonts.
As a fix this commit deprecates `$o-fonts-path` and replaces it with
`$o-fonts-build-service-path`, to specify a Build Service url to load
fonts from – this could be customised to point to a different version
of …
> fix: o-fonts, support self hosted fonts

- .github/workflows/release-please.yml
- scripts/publish.js
This reverts commit 170c31f39d3e82a188e40dd0818c60dd2419976f.
See PR: https://github.com/Financial-Times/origami/pull/747
`steps.release.outputs` is a "map" [what kind of map? that's what I
would like to know] of outputs for a job and so the previous change
did not work and all releases fail.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
With this revert only releases which contain commits with
single quotes in the commit  messages will fail – I haven't
had time to figure out how to escape them yet
> Revert "backstage: handle single quotes in commit messages on release"

- libraries/o-errors/README.md
Note: I didn't use "docs" for the conventional commit as that doesn't trigger a release but we need to make a release for doc changes to show up in the registry, unfortunately. 
FYI. Release github action broken. Depends on: https://github.com/Financial-Times/origami/pull/754
> fix: Correct o-errors import docs.

- libraries/o-tracking/README.md
- libraries/o-tracking/src/javascript/core/send.js
- libraries/o-tracking/test/main.test.js
* The Apps team sends non live events to a splunk index specifically for test data. Thus we need to ensure our development events have `is_live: false`. 
* In old versions of o-tracking we were able to set `is_live` in the initialisation config. This is no longer possible -  https://github.com/Financial-Times/origami/commit/5b69c97aa5d015046b26fc7d95aaa3b3852bf462
* The App started using the intended `test` config option but developers are finding the o-tracking debug logs particularly noisy (and our `ft-app` console can already be a little noisy sometimes 😬) 
* This option was discussed https://financialtimes.slack.com/archives/C02FU5ARJ/p1657105962524879. 
* I've added an additional config option to trigger `is_live: false` while leaving the `test` implementation as intended. 
* I found …
> feat: o-tracking, add test mode minus debug logs

- components/o-buttons/.npmignore
- components/o-buttons/src/tsx/button.tsx
- components/o-buttons/stories/button.stories.tsx
As part of slowly rolling out TSX templates. Let's allow Spark to experiment with the o-buttons tsx template, if they would like :)  https://github.com/Financial-Times/spark/pull/2410#discussion_r927528465
> feat: publish o-buttons tsx

- components/o-buttons/src/tsx/button.tsx
hello!
changes in this pr:
- remove `ButtonTemplate` (it fails to compile because of the lack of overlap in the union)
- add a `makeClassNames` function to reduce some of the duplication between LinkButton and Button created by removing ButtonTemplate
- attach the `onClick` handler ourselves to handle React runtime expecting the handler to be a `MouseEventHandler` rather than a function, this should always work without requiring a `import type {} from "react"` in the agnostic templates
- use `null` as the default value for `href` so we can do `href={href}` rather than `{...(href ? {href} : {}}`. functionally the same i think but looks a little prettier
> alter o-buttons tsx to solve compile failures in stricter environments

- apps/website/RUNBOOK.md
This has been bugging me for some time as the website isn't all of origami and it might be useful to repurpose the `origami` code to e.g. be used for changelogs for the origami project
I will take care of fixing up biz ops data for you if you approve this
> Change origami code to origami-website

- components/o-cookie-message/README.md
- components/o-cookie-message/demos/src/custom-html-full.mustache
- components/o-cookie-message/src/js/cookie-message.js
- components/o-cookie-message/src/scss/_mixins.scss
- components/o-cookie-message/src/tsx/cookie-message.tsx
- components/o-cookie-message/test/helpers/fixtures.js
See issue for more details:
https://github.com/Financial-Times/origami/issues/506
Requires users to update their markup.
>The focus order is incorrect inside the component, this issue may
>affect keyboard only users who would expect the focus order to be
>sequential from top to bottom, left to right.
Uses the flexbox `order` property to ensure this is not a visually
breaking change. Both old and new markup order will continue
to work.
closes: https://github.com/Financial-Times/origami/issues/506
> fix: o-cookie-message, fix tab order

- components/o-topper/package.json
- package-lock.json
upgrade n-map-content-to-topper version in order to be able tu use alphaville branding
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1316?modal=detail&selectedIssue=CI-1158)
> fix: upgrade n-map-content-to-topper version in o-topper

- components/o-spacing/stories/spacing-demo.tsx
- components/o-spacing/stories/spacing.scss
- components/o-spacing/stories/spacing.stories.tsx
- package-lock.json
I do not think it makes sense to provide public tsx templates for o-spacing
e.g. demo....
e.g. html (with different props to demo screenshot above)...
"demo" indicates demo css. I chose to use o-spacing css custom props which a user could copy from the html tab
> docs: add o-spacing storybook

- apps/website/_includes/footer.html
- components/o-cookie-message/MIGRATION.md
- components/o-cookie-message/README.md
- components/o-cookie-message/demos/src/custom-html-full.mustache
- components/o-cookie-message/src/js/cookie-message.js
- components/o-cookie-message/src/tsx/cookie-message.tsx
- components/o-cookie-message/test/helpers/fixtures.js
- components/o-footer-services/MIGRATION.md
- components/o-footer-services/README.md
- components/o-footer-services/demos/src/footer-content-only.mustache
- components/o-footer-services/demos/src/footer-legal.mustache
- components/o-footer-services/demos/src/footer-links.mustache
- components/o-footer-services/demos/src/footer-logo-content.mustache
- components/o-footer-services/demos/src/footer-logo.mustache
- components/o-footer-services/demos/src/footer-no-content.mustache
- components/o-footer-services/demos/src/footer.mustache
- components/o-footer/demos/src/simple-footer.mustache
- components/o-header/stories/storybook-data/anon.ts
- components/o-header/stories/storybook-data/user.ts
- components/o-layout/demos/src/shared/footer.mustache
Closes: https://github.com/Financial-Times/origami/issues/785
> fix: add missing Slavery Statement & Policies to footer demos / docs

- components/o-banner/demos/src/demo.scss
- components/o-banner/src/scss/_mixins.scss
- components/o-banner/src/scss/_variables.scss
When `$o-spacing-relative-units:true` o-banner would output a large negative position for the close button due to... bad math in Sass. Instead we can use the `calc` function.
> fix: o-banner, relative space close button position

- .github/workflows/percy.yml
- templates/percy-workflow.yml
It doesn't look like we are running Percy on merge to main as the action will only run if certain files have been changed, it seems to be misconfigured – perhaps from before we moved to a mono-repo, when each component would have its own Percy action.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
This may explain why Percy has not been showing visual diffs with the message:
> Multiple browsers were upgraded to the latest version in this build.
> Snapshots will show as "new snapshots" until the next build is
>created on the baseline branch.
We haven't been updating screenshots of the baseline branch (main)!
> backstage: Run the Percy Github action on merge to main

- components/o-expander/README.md
- components/o-expander/demos/src/collapsing-height.mustache
- components/o-expander/demos/src/collapsing-hidden.mustache
- components/o-expander/demos/src/collapsing-list.mustache
- components/o-expander/demos/src/collapsing-selector.mustache
- components/o-expander/demos/src/hidden-content.mustache
- components/o-expander/demos/src/pa11y.mustache
- components/o-expander/demos/src/toggle.mustache
- components/o-expander/main.scss
- components/o-expander/package.json
- components/o-expander/src/js/expander-utility.js
- components/o-expander/src/tsx/expander.tsx
Note: we do not enforce the new copy using JS as we cannot know where users
place their target relative to the content they reveal. This copy is only
needed when the target is placed below the revealed copy. In the future
we should consider redesigning this pattern for a more typical
disclosure pattern.
closes: https://github.com/Financial-Times/origami/issues/513
> fix: o-expander, advertise where content is added to screen reader users

- apps/storybook/config/main.js
- components/o-labels/stories/core/content.stories.tsx
- components/o-labels/stories/core/indicators.stories.tsx
- components/o-labels/stories/core/life-cycle.stories.tsx
- components/o-labels/stories/core/timestamps.stories.tsx
- components/o-labels/stories/internal/colour-pallet.stories.tsx
- components/o-labels/stories/internal/content.stories.tsx
- components/o-labels/stories/internal/service-tier.stories.tsx
- components/o-labels/stories/internal/support.stories.tsx
- components/o-message/stories/core/message-notice.stories.tsx
- components/o-message/stories/internal/message-action.stories.tsx
- components/o-message/stories/internal/message-notice.stories.tsx
- components/o-message/stories/message-alert.stories.tsx
- components/o-message/stories/shared/message-notice.tsx
- components/o-message/stories/whitelabel/message-notice.stories.tsx
Looks like our Storybook setup is a little borked. We used a dynamic includeStories property to include different stories depending on which brand we’re building the StoryBook for, It works fine locally but the prod build errors because Storybook uses static analysis during the prod build to determine which stories to include/exclude – it doesn’t execute the code, just looks for an array or regex. Looks like someone reported the same issue / expectations as us back in Jul.
Is only an issue when `storyStoreV7` or `buildStoriesJson` is enabled in storybook config. `storyStoreV7` will be the default in the future. So instead of using a dynamic `includeStories` property let's include stories based on directory structure:
`stories/*.stories.tsx` - stories for all brands …
> fix: storybook build / brand unique stories

- components/o-labels/src/tsx/label.tsx
It was not possible to use templates with custom labels. To support this we can allow any state on the BaseLabel tsx component.
```scss
@include oLabelsAddState('some-example', (
'background-color': oColorsByName('claret')
));
```
```jsx
<BaseLabel state="some-example" size="big">my custom label</BaseLabel>
```
> feat: o-labels, support custom labels with tsx templates

- components/o-labels/README.md
- components/o-labels/demos/src/indicators-badge.mustache
- components/o-labels/main.scss
- components/o-labels/origami.json
- components/o-labels/src/scss/_mixins.scss
- components/o-labels/src/tsx/label.tsx
- components/o-labels/stories/core/indicators.stories.tsx
- package-lock.json
This style is already duplicated in the homepage and live blogs app. The Spark team would also like to use this style in the live blogs preview page.
on the homepage:
on the live stream page:
> feat: Add support for a "badged" variant of live and close labels.

- components/o-labels/src/scss/_mixins.scss
- components/o-labels/src/scss/_variables.scss
This was flagged in a DAC audit as distracting, with no way to turn it off except for by setting prefers-reduced-motion maybe – and who knows that exists.
This will impact places the live indicator is used including:
- ft.com homepage
- ft.com live news page
- ft.com article page (via live teaser)
- ft-app
- spark preview
https://financialtimes.atlassian.net/browse/AACERT-27
> fix: remove blinking animation from live label

- components/o-cookie-message/src/js/cookie-message.js
- components/o-cookie-message/src/scss/_mixins.scss
- components/o-cookie-message/test/helpers/fixtures.js
This PR is to improve reflow accessability of the cookie banner in `o-cookie-message` by reducing the size of padding when viewport size is 320px.
JIRA ticket: https://financialtimes.atlassian.net/browse/ADSDEV-1204
> ADSDEV-1204 Cookie Banner DAC_Reflow_06

- components/o-cookie-message/README.md
- components/o-cookie-message/demos/src/custom-html-full.mustache
- components/o-cookie-message/src/js/cookie-message.js
- components/o-cookie-message/src/scss/_mixins.scss
- components/o-cookie-message/test/helpers/fixtures.js
- Reverses `o-cookie-message__content-outer` [markup addition](https://github.com/Financial-Times/origami/pull/861) before release. We can't add new markup without a major release, as it requires some users to update their markup – including ft.com projects. These don't rely on o-cookie-message JS to generate cookie message markup as they require a progressively enhanced fallback for when JavaScript has failed for whatever reason.
- Instead this PR adds overflow CSS to the existing `o-cookie-message__inner` element.
- The original addition of `o-cookie-message__content-outer` caused the separate [cookie message copy change PR](https://github.com/Financial-Times/origami/pull/858) to conflict. It was convenient to cherry pick that commit here.
> cookie message fixes

- apps/storybook/config/main.js
This option has broken our production Storybook Build with error:
>Uncaught ReferenceError: regeneratorRuntime is not defined
I tried configuring `browserlist` in webpack in an attempt to:
1. remove polyfills for features like `async/await` by building for modern browsers
2. add polyfills for features like `async/await` by building for older browsers
No luck.
At this point, I'm not sure what is calling `regeneratorRuntime` or whether `regeneratorRuntime` is in a pre-compiled bundle or not.
How about we wait until `storyStoreV7` isn't an experimental feature and storybook v7 and related pugins are released:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#modern-browser-support
> docs: Do not use Storybook `storyStoreV7` for now.

- components/ft-concept-button/main.scss
- components/ft-concept-button/src/tsx/concept-button.tsx
- components/ft-concept-button/stories/concept-button.scss
- components/ft-concept-button/stories/concept-button.stories.tsx
- components/ft-concept-button/stories/concept-link.stories.tsx
1. Hide the current concept button styles from Origami because it is not used
and is a candidate for deprecation. That style seems to be only still used in
one place, via n-myft-ui, on the contact preferences page. In addition it is a
link, not a button, like the one here in Origami.
2. Add ft-concept-button__link to fulfil the same purpose as the above but
on the newsletter page. This will be the preferred style going forward. It's
teal to match the colour of our links.
> feat: Add link variant to ft-concept-button 

- package-lock.json
- scripts/component/watch.bash
Rebuild watched components when any component / library changes. E.g. `npm run watch -w components/o-forms` will rebuild when o-normalise is updated.
> backstage: locally watch for any component / library change

- components/o-topper/src/scss/_mixins.scss
- components/o-topper/src/scss/themes/_full-bleed-image.scss
- components/o-topper/src/scss/themes/_split-text.scss
Background on toppers caption is not necessary and at some point was causing some visual issues with right-rail. 
With this PR we fix that.
> fix: remove background from figcaption on toppers

- components/o-topper/README.md
- components/o-topper/demos/src/full-bleed-image-center.mustache
- components/o-topper/demos/src/full-bleed-image-left.mustache
- components/o-topper/demos/src/full-bleed-offset-right-rail.mustache
- components/o-topper/demos/src/full-bleed-offset.mustache
- components/o-topper/demos/src/split-text-center.mustache
- components/o-topper/demos/src/split-text-left.mustache
- components/o-topper/src/scss/_elements.scss
- components/o-topper/src/scss/_mixins.scss
- components/o-topper/src/scss/_variables.scss
- components/o-topper/src/scss/themes/_full-bleed-image.scss
- components/o-topper/src/scss/themes/_full-bleed-offset.scss
- components/o-topper/src/scss/themes/_split-text.scss
- tools/a11y/index.js
add element image-caption replacing  image-credit behaviour and modify image-credit as it was before the las change , that is, set image-credit on top of the image on the bottom right corner with white color and shadow.
At the moment this is meant to be used on articles showing image-caption or image-credit but not showing both even thought we have prepared this for use both at the same time and individually. In the images below AFTER we show with both just for comparing purposes.
[ticket1](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1316?modal=detail&selectedIssue=CI-1420)
[ticket2](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1316?modal=detail&selectedIssue=CI-1421)
[ticket3](https://financialtimes.atlassian.net/jira/software/c/proje …
> feat: add element image-caption replacing  image-credit behaviour and modify image-credit 

- components/o-topper/src/scss/_elements.scss
credit element is a little bit sliced when is running on browsers with permanent scroll bar. 
In this Pr we move a little bit to the left the element so they are able to see it completely
BEFORE
AFTER
> fix: show credit element on browser with permanent scroll

- components/o-labels/src/scss/_mixins.scss
- components/o-labels/src/scss/_variables.scss
This reverts commit 431aa6df44bcea50771841eb540a2cf3db51c299.
The powers that be have decided not to remove the blinking animation from the live label after all, instead we will update our accessibility statement regarding a means of disabling the blinking.
Relates to: https://financialtimes.atlassian.net/browse/CON-2112
> fix: revert "remove blinking animation from live label"

- components/o-comments/test/methods/stream/publish-event.js
Some o-comments tests began to fail consistently after Coral updated our staging instance to v7. The Storytelling team plan to work with Coral to revert that upgrade for now. In the meantime skip this test to un-block Origami team releases.
> backstage: o-comments, skip failing tests

- components/o-teaser/src/scss/themes/_hero.scss
closes: https://github.com/Financial-Times/origami/issues/918
> fix: o-topper, image hero meta contrast

- components/o-footer/src/scss/_mixins.scss
At some breakpoints links within o-footer are partially hidden when they overflow. This also means there are hidden footer links when zoomed or when a custom text spacing is applied – an accessibility issue.
Instead allow links to wrap, so no link copy is ever hidden.
close: https://github.com/Financial-Times/origami/issues/931
When this happens it is more difficult to skim links left to right, as links in each column may not be aligned. This isn't such an issue since links are categorised in columns. We may choose to undertake a broader change in the future to reduce this by:
1. Restoring the "More from the FT Group" link from its current position, in its own column, to sit on a new row spanning the footer's width.
2. Updating footer link columns to use just the space they need, rather …
> fix: o-footer, allow links to wrap rather than overflow with ellipses

- components/o-header/MIGRATION.md
- components/o-header/demos/src/grid-demo.mustache
- components/o-header/demos/src/header.json
- components/o-header/demos/src/header.mustache
- components/o-header/demos/src/mega-menu.json
- components/o-header/demos/src/pa11y.mustache
- components/o-header/demos/src/simple-header.mustache
- components/o-header/demos/src/sticky-header.mustache
- components/o-header/demos/src/subbrand.json
- components/o-header/demos/src/subbrand.mustache
- components/o-header/demos/src/subnav-right-align.json
- components/o-header/demos/src/subnav.json
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/tsx/drawer.tsx
This PR adds a migration guide and changes the class name for a divider in the drawer menu. Since we changed the markup of `o-header` we can apply the divider directly on `ul` tag instead of a list item itself.
> Migration guide and tsx templates

- components/o-overlay/src/js/overlay.js
- package-lock.json
This issue was discovered while resolving #902. In both cases, we use JS to trap the focus and we listen if the tab key is pressed. For voiceOver the user usually will use `ctrl-option-[left/right] Arrow` and focus would leave the modal. To fix this we followed [web standard recommendations](https://www.w3.org/WAI/ARIA/apg/patterns/dialogmodal/). 
One to note is that once the overlay modal is open it is not automatically focused.
> backstage: trap focus in overlay using role=dialog and aria-modal=true

- components/o-colors/src/scss/_functions.scss
This PR ensures that `oColorsMix` calls the sass-native `mix` function with the required % unit for its `$weight` argument.
`sass@^1.52.3` raises warnings for any calls to `mix` made with a unitless value. In a project like ft-app this results in the terminal becoming flooded with aggressive red messages.
> Convert unitless values into percentages in oColorsMix

- components/o-colors/main.scss
- components/o-colors/src/scss/_functions.scss
- components/o-colors/src/scss/_variables.scss
o-colors includes a map of colour names to hex values. It includes meta data for each colour, such as whether it is deprecated or not.
When a user requests a deprecated colour we output a warning to help them migrate.
A user can also request a deprecated colour without meaning to by requesting all o-colors styles with the `oColors` primary mixin. Even if they aren't using the deprecated colour they then get a warning. We have 3 options:
1. Continue to hound users about something they're not doing, untill they staty ignoring warnings.
2. Insist users are very specifc about which parts of o-colors they would like to include, force them to list each colour and colour usecase they use (not a very lovely user experience, not possible to enforce without a major release and  Build Service …
> fix: o-colors, reduce warnings

- components/o-header/src/tsx/drawer.tsx
- package-lock.json
Adds correct role to drawer to o-header tsx, as with demos. See abf34447eb7b2d51fe8ceb3c3cf02435635b43d5
> fix: o-header tsx, use correct drawer markup

- components/o-autocomplete/package.json
- components/o-buttons/package.json
- components/o-expander/package.json
- components/o-footer/package.json
- components/o-forms/package.json
- components/o-header-services/package.json
- components/o-header-services/test/js/drop-down.test.js
- components/o-header/package.json
- components/o-layout/package.json
- components/o-overlay/package.json
- components/o-share/package.json
- components/o-social-follow/package.json
- components/o-stepped-progress/package.json
- components/o-teaser/package.json
- components/o-typography/package.json
- components/o-video/package.json
- package-lock.json
Attempt 2 of f8d45ef723d178e33ee1b158c43ae9f745a97b19
> fix: ensure components depend on the latest o-normalise version

- components/o-topper/src/scss/themes/_deep-landscape.scss
Makes multiple styling changes to deep landscape:
- Moves the text down to the bottom of the image with padding
- Changes the link text to black in the header tags
- Removes the line between the heading
See: https://financialtimes.atlassian.net/browse/CI-1517
> fix: styling changes to deep landscape

- components/o-comments/src/js/stream.js
- components/o-comments/src/scss/coral-talk-iframe/main.scss
**Why ?** 
On the app the rem font size is different than in ft.com so we need to set a variant for the app to keep the same style.
**What ?** 
We set a new data-attribute called  data-o-comments-add-class which adds an additional class to coral component. On the app  we set the value data-o-comments-add-class="o-comments-app" and then it will take the styles that we have created for this class in this PR.
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?modal=detail&selectedIssue=CI-1460)
> feat: add option to set an additional class on shadow dom for o-comments

- components/ft-concept-button/README.md
- components/ft-concept-button/main.scss
- components/ft-concept-button/src/tsx/concept-button.tsx
This will be used first within o-topper on the article page, on white backgrounds. Typically Origami components use "inverse" themes to indicate a white foreground, for use on a dark background. However in this case ft-concept-button has an "inverse" theme already which is intended for use on claret backgrounds, and uses a claret text colour when clicked. We want an inverse theme that is also monochrome...
In storybook, when not pressed and pressed:
Design example in context, not pressed:
> feat: ft-concept-button, add inverse monochrome variant

- components/o-comments/src/js/stream.js
Why?
We have an issue on the app that provoques bad rendering on comments when they are more than 12 . With this option we can fix it and stablished what will be the parent scroll container of the comments which in some cases like in the app now or if they would be in a modal element ,would be needed to work properly 
What ?
We add an option data-o-comments-scroll-container to de component that contains a selector to get the element which is going to be the custom scroll container
> feat: add scrollContainer option on o-comments

- components/o-forms/README.md
- components/o-forms/src/js/forms.js
- components/o-forms/test/forms.test.js
- components/o-forms/test/helpers/fixtures.js
By default o-forms listens to submit events. It validates a form and, if it is valid, will then call submit on the form element. This means projects which use o-forms cannot prevent a valid form from submitting.
This may be desirable to add extra steps prior to submission. For example to load a captcha (~apparently this should happen on submit?~ which we want to run when the form is filled out correctly) or to display a final confirmation.
To achieve this option:
This PR introduces the `oForms.submit` event. This is fired by o-forms when its submit event handler has finished form validation, just before submitting the form. A user may listen for this event and prevent propagation to stop the form from submitting. As this would rely on the project's event listener running first, however, …
> feat: o-forms, allow submit events to be intercepted

- components/o-buttons/src/tsx/button.tsx
- components/o-buttons/stories/button.stories.tsx
This PR does not change the way o-buttons work.  It adds support for passing any string for the `icon` prop while still keeping the default icon sets as suggestions in IDE. This should improve TS users' experience with icons and also stop showing errors when custom icons are used.
There are a lot of eslint changes in the PR but the line that actually changed is line 23 in `button.tsx`
> Add any icon support to o buttons TSX template

- components/o-topper/README.md
- components/o-topper/demos/src/deep-landscape-left.mustache
- components/o-topper/src/scss/_mixins.scss
- components/o-topper/src/scss/themes/_deep-landscape.scss
- package-lock.json
We are introducing a Background Box variation for the deep landscape layout in toppers.
The  Background Box option is meant to improve readability when the text shadow is not good enough depending on the used background image chosen by Editorial. More information in the [ticket](https://financialtimes.atlassian.net/browse/CI-1543)
Desktop/Tablet (White and black permutations) 
Mobile (White and black permutations) 
In this PR:
* Add new background box modifier
* Fix the credit not appearing in the Deep Landscape demo
* Extending the existing demo to cover more permutation of the components
* Reducing to 16px the margin-bottom for all the headlines (Design request)
> feat: Background Box support in deep landscape

- components/o-topper/MIGRATION.md
- components/o-topper/README.md
- components/o-topper/main.js
- components/o-topper/package.json
- package-lock.json
`o-topper` no longer includes JavaScript to select the correct topper for JSON-formatted FT articles and flags. This helper was deeply tied to the FT.com content store, and included hardcoded UUIDs and business logic beyond the scope of Origami. Origami components focus on providing reusable user interfaces – without business logic assumptions which could limit their use outside specific groups or use-cases.
Not to mention, `n-map-content-to-topper` does not set its version number in `package.json` causing Origami contributors to have to `npm i` regularly for some reason – e.g. when checking out a new branch. Super annoying and time consuming.
**Review but do not merge yet:** Let's wait for [this topper change to be released](https://github.com/Financial-Times/origami/pull/1008), so we …
> Major o-topper release: remove JS including `n-map-content-to-topper` 

- components/o-topper/src/scss/themes/_deep-landscape.scss
fix margin bottom for box-shadow on deep-landscape to have 72px 
fix margin bottom on mobile on deep-landscape to have 24px
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?modal=detail&selectedIssue=CI-1601)
BEFORE
AFTER
> fix: set new margin bottom deep-landscape for desktop and tablet

- components/o-date/package.json
- components/o-date/test/date.test.js
- package-lock.json
Upgrades ft-date-format to enable use of FT editorial time style.
`t` can be used to format a time to match the style in FT's Style Guide.
> feat!: introduce FT editorial time formatting

- components/o-typography/src/scss/use-cases/_general.scss
- components/o-typography/test/scss/_mixins.test.scss
Anchor elements which open in a new context (tab/window) have some hidden copy in a pseudo element to let screen reader users know. This is visually hidden with absolute positioning and clipping. This may cause an issue if it has an ancestor with hidden overflow between it and whatever element on the page is its containing block. To avoid this, we set `position: relative` on the anchor element to ensure it is always its containing block and so any ancestor with hidden overflow will clip it.
[CodePen Demo](https://codepen.io/ft-origami/pen/zYJJRgj?editors=1100)
Issue shows up in a large o-table with many rows, which contain links which open in a new context:
https://www.ft.com/ft1000-2023
https://user-images.githubusercontent.com/10405691/226403373-84bbc1d4-b12e-48a1-b209-8a9329a9473e.mp4 …
> fix: o-typography, position visually hiddent anchor content relatively [OR-148]

- components/o-video/src/js/video.js
I've found that in some videos the progress video event is not sent at some points. For example this [video page](https://ft.com:/video/3a6c06ee-14b7-4d6f-8b08-08cdd947c0a7?playlist-name=editors-picks&playlist-offset=0 ) sends progress events only until 98 percent , so 99 and 100 is not sent ever. 
Increasing this range to 5 points as the same of the other parts we want to capture progress event video we ensure that at least one of those points are capture.
> Capture progress video events

- components/o-forms/README.md
- components/o-forms/main.scss
- components/o-forms/origami.json
- components/o-forms/src/scss/_deprecated.scss
- components/o-forms/src/scss/main.scss
- components/o-forms/src/scss/modifiers/_custom.scss
Links which look like form inputs may be confusing for some users of assistive technologies, as they may be accessed or behave differently than expected. Further, unlike true o-forms radio inputs, there is no fieldset with legend to group the links.
Instead use a standard box style radio button:
https://github.com/Financial-Times/origami/issues/535
> fix: o-forms, deprecate pseudo-radio-link [OR-62]

- components/ft-concept-button/src/js/ft-concept-button.js
The ft-concept-button sets it’s aria-label based on whether the button has been pressed or not. However, initially the button has no aria-label (unless it has been set directly in the mark-up), it only gets set when the isPressed function is called on toggle. So when the page loads, there are no aria-labels.
Ideally, default aria-labels should be set directly in the markup/html, however, we can add some code to defensively add this, if it hasn't been.
If you add this.isPressed = this.isPressed; into the constructor, it will set the aria-label when the button is initialised. 
We should be adding aria-labels directly to the markup, but I think this code is still work adding, in case aria-labels haven't been added
> fix(concept-button): sets aria-label on initialise

- components/o-header/package.json
- components/o-header/src/js/subnav.js
- package-lock.json
1. Viewport resize: Previously, o-header would only respond to viewport resize if the user had initialised `o-viewport`. This was undocumented. Let us always initialise `o-viewport` and include it as a dependency.
2. Viewport resize part 2: The wrapper width was calculated and stored on initialisation. This value is then wrong after resize, breaking the calculation to decide whether to show scroll buttons.
3. DOM mutation: When subnav items change, recalculate subnav scrollability. This supports single page application (or similar), where navigation items are updated dynamically.
> fix: o-header, subnav, improve scroll button behaviour.

- components/o-forms/main.scss
When including o-forms CSS partially, e.g:
```scss
@include oForms($opts: (
'elements': (
'textarea',
'radio-round'
)
));
```
o-forms would error. That's because we introduced `@each` to iterate over `$themes` which in this case is `null`. Sass will treat this as a 1 item list and `$theme` will be null:
https://github.com/Financial-Times/origami/pull/1088/files#diff-7d687f8781b6320c740149112f175979087161f2decef8e0a7d6c76243ff67feR150
To avoid this check if the user has set the themes option and, if they haven't, set themes to an empty list.
Closes: https://github.com/Financial-Times/origami/issues/1105
> fix: o-forms, do not error when no themes given to primary mixin

- components/o-comments/src/js/stream.js
change the way to obtain scrollContainer element. 
Why ? Previously we were using document.querySelector which on the app was getting a wrong element since there were several elements/containers with that class. This way we ensure that we are getting the container which is parent of the element where the comments are in
> fix: way obtain scrollContainer element

- apps/website/_components/versioning.md
The Accounts team would like to deprecate `n-sliding-popup` however we have no documentation on how to do that. We used to! I found it on archive.org: http://web.archive.org/web/20180227070914/http://origami.ft.com/docs/component-spec/modules/#deprecation-of-a-module
I have re-written these to be: accurate with current systems; more flexible (appropriate release communication varies); and concise.
> docs: Add guidelines for releasing (and deprecating) a component.

- components/o-tooltip/README.md
- components/o-tooltip/demos/src/professional-demo.mustache
- components/o-tooltip/main.scss
- components/o-tooltip/origami.json
- components/o-tooltip/src/js/tooltip.js
- components/o-tooltip/src/scss/_brand.scss
- components/o-tooltip/test/Tooltip.test.js
- components/o-tooltip/test/helpers/fixtures.js
The second commit here makes sure the FT Professional theme (or any custom theme) can be applied imperatively via the JavaScript API – where tooltip markup is generated for the user
> [OR-163] Add a tooltip theme for FT Professional

- components/o-forms/src/scss/modifiers/_inverse.scss
- components/o-forms/src/scss/shared/_validity.scss
This PR updates the selector that applies the red border and text color to inputs, textareas, and selects, to target these elements even if they're not marked as invalid by browser validation (with the `invalid` pseudo-class).
See https://financialtimes.slack.com/archives/C02FU5ARJ/p1685436315480479 for context.
> feat: apply invalid input styles to inputs without browser validation

- components/o-forms/stories/boxRadioBtns.stories.tsx
- components/o-forms/stories/checkboxes.stories.tsx
- components/o-forms/stories/radioBtns.stories.tsx
Remove the empty string as a key and instead use undefined. It seems that an empty string as a value for storybook controls does not work. The bad part is that the storybook does not errors or give us warning about them and fails other controls to render for other components. We should just use undefined as means for the user to go back default style. 
We could also not have an option for users to go back to default styling (mostly meaning initial render) but that seems like a bad user experience while exploring the components. 
This PR should fix the issues with controls for storybook components.
> fix: fix how we render storybook select labels.

- components/o-autocomplete/README.md
- components/o-autocomplete/demos/src/dynamic-custom-suggestion/data.js
- components/o-autocomplete/demos/src/dynamic-custom-suggestion/dynamic-custom-suggestion.js
- components/o-autocomplete/demos/src/dynamic-custom-suggestion/dynamic-custom-suggestion.mustache
- components/o-autocomplete/origami.json
- components/o-autocomplete/src/js/autocomplete.js
- package-lock.json
I'm trying to use o-autocomplete in our TagMe rewrite. However, TagMe (which doesn't currently use origami) has some custom rendering of it's suggestions, with additional context to help editorial decide which tag to choose.
Don't know if this is the best way - but allow the user to override the `suggestionTemplate` function. Open to better ideas, or if I should even be using this component!
This seems to work well enough. The only situation it doesn't work in is with the defaultValue (which is a string), but this can be compensated for in the override function itself.
> feat: autocomplete, add a suggestionTemplate override option

- components/o-typography/README.md
Using the below import statement results in a build error:
```js
import oTypography from 'o-typography';
```
```
ERROR in ./client/scripts/main.js
Module not found: Error: Can't resolve 'o-typography' in '{path}/next-newsletter-signup/client/scripts'
@ ./client/scripts/main.js 6:0-39 7:24-35
```
This resolved by changing the import statement to:
```js
import oTypography from '@financial-times/o-typography';
```
> docs: update o-typography README 'Constructing o-typography' instructions

- components/o-header-services/src/tsx/header-services.tsx
- components/o-header-services/stories/fixtures.tsx
Added the ability to pass JSX Elements into relatedContent for o-header-services. Also fixed the bug where the relatedContent `href` was set to be the label.
> feat: Allow JSX Elements to be passed in as relatedContent

- apps/astro-website/src/components/header/Header.astro
- apps/astro-website/src/components/header/NavItem.astro
- apps/astro-website/src/components/header/SecondaryNav.astro
- apps/astro-website/src/layouts/Layout.astro
- apps/astro-website/src/pages/index.astro
The header component now automatically generates secondary navigation. Ancestors and children for secondary nav are determined based on the path you are on the URL. This ignores the `/` url and `[slug]` paths.
> Add header component

- .github/workflows/release-please.yml
It does not look like we need to make any changes: https://github.com/google-github-actions/release-please-action/releases/tag/v3.0.0
> chore: update release please

- components/o-icons/README.md
Release Please is [trying to release o-icons v8 ](https://github.com/Financial-Times/origami/pull/1227) due to an incorrect commit message in our history. It keeps trying. I wonder if explicitly requesting the release of o-icons current version will prevent this, or... cause more problems.
Let's find out.
https://github.com/googleapis/release-please#how-do-i-change-the-version-number
> chore: o-icons, release 7.6.0 not 8.0.0

- components/o-social-follow/README.md
- components/o-social-follow/demos/src/social-follow.mustache
- components/o-social-follow/package.json
- components/o-social-follow/src/scss/_variables.scss
- components/o-social-follow/src/tsx/social-follow.tsx
I decided to make this a minor release, without removing Twitter from the API entirely, as SVG is not currently inlined for this component. It's already using the `x` logo from the Image Service update and we only need to replace the twitter blue with black.
> fix: o-social-follow, update Twitter branding to X [OR-296]

- components/o-forms/README.md
- components/o-forms/demos/src/ft-live.mustache
- components/o-forms/main.scss
- components/o-forms/origami.json
- components/o-forms/src/scss/shared/_brand.scss
- components/o-forms/src/tsx/Form.tsx
- components/o-forms/src/tsx/RadioBtns.tsx
- components/o-forms/stories/boxRadioBtns.stories.tsx
- components/o-forms/stories/checkboxes.stories.tsx
- components/o-forms/stories/radioBtns.stories.tsx
Radios round, radios square, and checkboxes. E.g.
Figma Library updates to follow:
https://financialtimes.atlassian.net/browse/OR-314
> feat: o-forms, add ft-live subbrand [OR-314]

- components/o-buttons/README.md
- components/o-buttons/demos/src/demo.scss
- components/o-buttons/demos/src/ft-live.mustache
- components/o-buttons/origami.json
- components/o-buttons/src/scss/_brand.scss
- components/o-buttons/src/scss/_variables.scss
- components/o-buttons/src/tsx/button.tsx
This includes primary, secondary, and ghost buttons. As well as things like pagination and disabled states. E.g.
Figma updates to follow: 
https://financialtimes.atlassian.net/browse/OR-313
> feat: o-buttons, add ft-live subbrand [OR-313]

- components/o-typography/README.md
- components/o-typography/demos/src/ft-live-links.mustache
- components/o-typography/main.scss
- components/o-typography/origami.json
- components/o-typography/src/scss/_brand.scss
- components/o-typography/src/scss/use-cases/_general.scss
E.g.
Figma updates to follow: 
https://financialtimes.atlassian.net/browse/OR-315
> feat: o-typography, add ft-live sub-brand support for links [OR-315]

- components/o-cookie-message/README.md
- components/o-cookie-message/demos/src/custom-html.mustache
- components/o-cookie-message/src/js/cookie-message.js
- components/o-cookie-message/src/tsx/cookie-message.tsx
- components/o-cookie-message/test/helpers/fixtures.js
- package-lock.json
Adding `data-nosnippet` to cookie-message to ensure that its content is not used by google as the description on SERP. 
https://financialtimes.atlassian.net/browse/CPREL-782
> CPREL-782: Stop cookie banner content showing in SERP page description

- components/o-overlay/src/js/overlay.js
- components/o-overlay/src/scss/_mixins.scss
- package-lock.json
Typically one h1 on a page helps create a navigatable structure. There Is No Document Outline Algorithm.
https://adrianroselli.com/2016/08/there-is-no-document-outline-algorithm.html#Update10
But I wasn't sure what the right answer is now we have `aria-modal` that can trap focus and mark other elements as inert, and went on a little side quest.
Turns out W3C's APG Task Force (ARIA Authoring Practices Guide) discussed this in a meeting a few years ago. https://github.com/w3c/aria-practices/issues/551#issuecomment-365134527
They concluded:
- It is helpful if there is a consistent approach across dialogs in an application.
- There is not necessarily a need for the APG to prescribe a specific approach.
So, I guess provided you're in a modal either h1 or h2 is fine.
APG continue to use h2 in …
> fix: o-overlay, which to a h2 header

- components/o3-button/package.json
- components/o3-web-token/package.json
Origami components do not require node except for development, so we decided to remove engines.node to avoid warnings when users are building components with another node version. The origami repo is a mono repo, so we can rely on the root engines.node for development. Components do require a flat dependency tree, enforced through peer dependencies, so we change engines.npm to a permissive >7.
> fix: Remove "engines.node" from o3 components

- release-please-config.json
- scripts/regenerate-ci-config-files.js
It looks like release-please is failing to find all tags to represent recent releases, looking through the last 500 commits, and making incorrect release PRs. This effectively blocks us from releasing components.
"[last-release-sha] can be useful when you've accidentally merged a bad release PR" as it will "set the commit sha release-please will use from which to gather commits"
https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
> fix: release-please, set "last-release-sha"

- package-lock.json
- tools/create-component/package.json
Tool was throwing errors unexpectedly, this appears to have been in `main` for quite a while. This change adds `ts-node` as a dev dependency to fix this issue.
> backstage: fix testing for tool create-component

- scripts/build-website.bash
build-website is failing when it tries to `cd` into the old storybook directory. As this no longer exists, it fails every build.
> fix: remove storybook building from build-website.bash

- apps/astro-website/redirects.js
Removing Storybook from the website build process broke the links to Storybook. As a fix we will point to the new instances hosted on chromatic.
> fix: link astro's storybook links to chromatic

- apps/astro-website/src/pages/storybook.astro
Storybook's composition instance gives a better experience to our users by bringing all of our brands into one Storybook instance. Linking to the headings for each brands will help users see that other brand options are available within storybook should they wish to browse them.
> backstage: link to storybook composition instance

- components/o-multi-select/README.md
- components/o-multi-select/src/js/multi-select-options.js
- components/o-multi-select/src/js/multi-select.js
- components/o-multi-select/src/tsx/multi-select.tsx
- components/o-multi-select/stories/multi-select.stories.tsx
Currently we use a string label to create the multiselect option elements. When one of these labels has a whitespace character, it cannot be removed, as querySelector doesn't find the element with the whitespace in the ID.
This change adds a new optional "key" to the TSX template (allowing users of the TSX to have a different value to the label), and ensure the value is used for creating the ID (rather than the label).
**Context: ** we want to use this in Spark for selecting categories for Specialist articles, however those categories sometimes have spaces (e.g. "Policy & Regulation"). Ideally, we'd use the category's UUID as the value, and the label as "Policy & Regulation").
N/A
N/A
> fix: allow for multiselect options with whitespace

- components/o-multi-select/src/js/multi-select-options.js
- components/o-multi-select/src/js/multi-select.js
I've been writing tests using react-testing-library for my usecase of the multiselect but have struggled because the option's innerText was undefined. Apparently innerText is not implemented in jsdom so this PR changes to use `textContent` instead.
> fix: Use textContent rather than innerText

- apps/for-everyone-website/src/content/docs/components/buttons.mdx
- apps/for-everyone-website/src/content/docs/professional/components/buttons.mdx
- apps/for-everyone-website/src/content/docs/sustainable-views/components/buttons.mdx
Changes `hello` to `Hello` on example buttons to match the documentation rules on casing
> docs: correct case for example buttons

- apps/for-everyone-website/astro.config.mjs
- apps/for-everyone-website/src/components/ThemeProvider.astro
The changes introduced in the last for-everyone PR (https://github.com/Financial-Times/origami/pull/1396) meant that Starlight loaded its stock `ThemeProvider` component, which will automatically set light or dark mode depending on the 'prefers-color-scheme' media query (essentially, whatever your machine's dark or light mode setting).
This PR fixes this, and uses a custom `ThemeProvider` that just tells Startlight to always show a light theme.e
https://financialtimes.atlassian.net/browse/OR-482
N/A
> Force light mode in for-everyone site

- components/o3-button/main.css
- presets/stylelint-config-origami-component/config.js
- presets/stylelint-config-origami-component/test/integration/config.test.js
This didn't work how I expected based on previous experience. I expected forced colours to remove the mask image. Instead, it seems we need to update the colour only. I expected `currentColor` to respect the forced colour, but that doesn't seem to be the case either. Perhaps because:
>The browser-specified values do not affect the style cascade; the values are instead forced by the browser at paint time.
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors#usage_notes
Instead I used a media query to set the icon colour to `ButtonText` or `LinkText` according to whether we have an `a` or `button` tag.
Here's an example in Windows with different contrast modes enabled:
I got a linting error for using `a` and `button` selectors. I think we should remove that rule. See commit …
> Fix o3-button icons with forced colours (such as given Windows High Contrast mode)

- apps/dictionary/tokens/internal/base/color.json
- apps/for-everyone-website/README.md
- apps/for-everyone-website/astro.config.mjs
- apps/for-everyone-website/src/components/ContentPanel.astro
- apps/for-everyone-website/src/content/docs/internal/components/buttons.mdx
- apps/for-everyone-website/src/content/docs/internal/guides/colours.mdx
- libraries/o3-tooling-token/build/internal/_variables.js
> [!NOTE]  
> This PR is a draft pending an exploration into a better and less-duplicate-y approach to supporting brands in the site
This PR adds the 'internal' brand to the for-everyone website, making it available as an option in the brand picker.
The steps for adding a new brand are as follows:
* Add a new 'locale' to `astro.config.mjs` for the new brand
* Tell the `ContentPanel` component which CSS file to load when this language/brand is set as active
* Copy all components over from an existing brand, switching out the brand-specific CSS file import for that component, and updating the Figma and Storybook links
* Copy other documentation mdx files that contain brand-specific content or styles that have to be manually set
👆 _Of these, that last step could absolutely be improved!_
> Add 'internal' brand to for-everyone site

- components/o-autocomplete/stories/data.js
- components/o-autocomplete/stories/dynamic-complex.stories.tsx
- components/o-autocomplete/stories/dynamic-delayed.stories.tsx
- components/o-autocomplete/stories/dynamic.stories.tsx
- components/o-autocomplete/stories/readme.stories.mdx
- components/o-autocomplete/stories/static.stories.tsx
Surfaces o-autocomplete demos in Storybook.
Future registry/o2-storybook migrations may be automated. But this PR was done manually and discovered the following areas to pay particular attention to when migrating demos:
* Comments appear in HTML/templating syntax, and are not compatible with JSX, these will need transforming.
* Some tags that should be self-closing are not. Which throws up errors when compiling JSX.
> docs: display o-autocomplete demos in O2 Storybook

- components/g-audio/package.json
- components/g-audio/stories/block.stories.tsx
- components/g-audio/stories/inline.stories.tsx
- components/g-audio/stories/readme.stories.mdx
Moves registry demos for g-audio to O2 storybook.
The demos are iframed from the build service, this is the path of least resistance to get the demos in storybook.
[OR-517](https://financialtimes.atlassian.net/browse/OR-517?atlOrigin=eyJpIjoiOGRmMzliMWYwODRiNDYwYjk0N2NkMDAzZTM2MDY0NGEiLCJwIjoiaiJ9)
[OR-517]: https://financialtimes.atlassian.net/browse/OR-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: display g-audio demos in o2-storybook

- components/o-comments/src/scss/coral-talk-iframe/main.scss
- package-lock.json
o-comments coral-talk-iframe SASS file
As per https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?issueParent=420949&selectedIssue=CI-2030, if you press the Report button in the comments section, and its state becomes aria-pressed="true", the background goes teal but it is not making the text white, and therefore you have teal text on a teal background. This because there is another selector for `span` and `i` (line 241-244) that keeps the color as teal. This change ensures that nested `span` and `i` also get the right colors.
https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?issueParent=420949&selectedIssue=CI-2030
NA bug fix
> fix: ci-2030 report button text color change on aria-pressed

- apps/dictionary/scripts/build-config/utils.js
Building tokens that include the `fontFamily` type previously did not correctly transform, resulting in the value being a string without quotes. Adding the Tokens Studio transform for this fixes this.
Below illustrates the issue:
**
**
> fix: transform fontFamily values when building tokens

- .github/workflows/o2-chromatic.yml
Previous path filters would only allows components prefixed with `o-*` to trigger the Chromatic Github Actions script. Meaning changes to components such as `g-audio` or `ft-concept-button` would never trigger a new release.
This PR instead triggers on all changes within `components/` except directories prefixed with `o3-*`.
> fix: exclude o3 components from o2-chromatic deployments

- components/o-comments/src/scss/coral-talk-iframe/main.scss
This is a follow-up to https://github.com/Financial-Times/origami/pull/1450 - the `&` resulted in a lot more selectors being pulled through than I expected, so I've gone to something more static
https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?assignee=5be57e310e625003a46e9693&selectedIssue=CI-2084
N/A
> fix: ci-2084 SASS was outputting more styles for & than expected

- README.md
- components/o-date/README.md
- components/o-date/src/js/date.js
- components/o-date/src/tsx/date.tsx
- components/o-date/stories/date.stories.tsx
- components/o-date/test/markup.test.js
An additional optional setting in o-date config to allow users to specify either sentence case or upper case for the text produced by using a data attribute.
https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?assignee=5be57e310e625003a46e9693&selectedIssue=CI-2129
https://financialtimes.slack.com/archives/C02FU5ARJ/p1709116210339189
N/A
Before
After
> feat: ci-2129 o-date allow users to set text case

- components/o-header-services/src/tsx/header-services.tsx
- components/o-header-services/src/tsx/navs.tsx
* simplify `hasHamburgerMenu`'s type to `boolean`
* reference `parentNode` instead of `parent` 
`hasHamburgerMenu`'s type was being inferred as `boolean | NavItem[]`. ~~Which was causing issues with how the storybook services were being displayed in the composition layer.~~
The true cause was that `parent` was being referenced instead of `parentNode`, no `parent` was in scope meaning the browser's `parent` was being referenced causing some issues.
[OR-576](https://financialtimes.atlassian.net/browse/OR-576)
[OR-576]: https://financialtimes.atlassian.net/browse/OR-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: reference parentNode in o-header-services navigation

- apps/dictionary/scripts/build-config/build-component.js
- apps/dictionary/scripts/build-config/utils.js
Component tokens marked as 'source' in Tokens Studio were not included when building component tokens with style dictionary. Added as `includes` to our style dictionary config.
> backstage: fix component tokens building

- components/o-header/README.md
- components/o-header/src/scss/features/_subnav.scss
I have noticed the beginning of the nav items are not aligned with the beginning of the header. This PR includes a very small CSS change to fix this spacing issue.
Before:
(Notice how "WORLD" does not line up with "HOME")
After:
n/a
n/a
> feat: removing spacing of first subnav button

- scripts/publish.js
[release please started failing](https://github.com/Financial-Times/origami/actions/runs/8470256633/job/23207548734) last week. The packages were released but CI still failed. It seems that this was an issue with deprecating origami repo data. This PR removes part of the code that makes a request to origami repo data and this should fix the last failing part of the CI.
> fix: fix failing release please

- components/o-teaser/README.md
- components/o-teaser/src/scss/themes/_small.scss
- components/o-teaser/src/tsx/image.tsx
- components/o-teaser/stories/arg-types.ts
add post modifier , meant to be used in live blog posts.
At the moment affects the styles if the teaser has the layout small
This PR change the way to solve [CLS](https://web.dev/articles/cls) by using aspect ratio instead of padding property as it was using
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-2167)
> feat: add post modifier to teaser

- components/o3-foundation/README.md
- components/o3-foundation/normalise.css
- We're removing the `.o3-clearfix` style definition from our `o3-foundation` package because it was outputting invalid CSS.
- This was causing an error when attempting to transpile the package using the `sass-loader` package in NextJS as part of the work in this pull request: https://github.com/Financial-Times/pro-central-banking/pull/134
- Removing the class in question was preferred due to the clearfix technique being rarely used these days. The functionality can be added back in the future if needed. 
- A search across the FT org was carried out and there are no known usages of the `.o3-clearfix` class.
> Remove o3-clearfix due to it causing the build to output broken css

- components/o3-button/main.css
- components/o3-button/stories/core/button.stories.tsx
- components/o3-button/stories/core/professional/button.stories.tsx
- components/o3-button/stories/internal/button.stories.tsx
- components/o3-button/stories/story-templates.tsx
- components/o3-button/stories/sustainable-views/button.stories.tsx
- components/o3-button/stories/whitelabel/button.stories.tsx
As part of migrating https://github.com/Financial-Times/pro-central-banking to `o3-button` in https://github.com/Financial-Times/pro-central-banking/pull/137 I needed to port across the existing `*--big` modifier for buttons and allow the setting of custom font-weights and padding.
- Sets up stories for `small` buttons in Storybook
- Allow customisation of `font-weight`
- Set `font-weight` to `700`
- Change `font-size` to `1rem`
> O3 Button | Big button support, custom font-weight

- components/o3-button/main.css
- components/o3-foundation/fonts.css
- components/o3-foundation/normalise.css
See commit messages for details. The below screenshot shows o3-button vs o-buttons
Horizontal padding differences are a conscious design choice
> Correct o3 font and button font size

- apps/for-everyone-website/src/content/docs/patterns/pagination.mdx
Currently shows undefined. Likely happened when we updated how we build TSX templates.
> fix: pagination button preview

- components/o-expander/src/js/expander-utility.js
- components/o-expander/src/js/expander.js
- components/o-expander/stories/nested-expander.stories.tsx
- components/o-expander/test/initialization.test.js
Expander was affecting to toggler buttons inside nested o-expander elements.
With this fix we exclude elements that are nested in other expander element.
I've added an example in storybook so we can test that scenario. Let me know if this is not needed
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-1976)
> fix:  do not affect nested expander elements

- apps/dictionary/tokens/core/use-case/color.json
- components/o3-foundation/src/css/tokens/core/_variables.css
- components/o3-foundation/src/css/tokens/core/professional/_variables.css
> fix: set o3 use case link inverse text colour

- components/o-autocomplete/src/js/autocomplete.js
This is a correction to changes introduced in https://github.com/Financial-Times/origami/pull/1524.
The deleted section of the comment became inaccurate when upgrading to `@financial-times/accessible-autocomplete` v3.0.0, which removed the `ariaLabelledBy` attribute in favour of the `menuAttributes` option. I raised this in a PR comment https://github.com/Financial-Times/origami/pull/1524/files#r1547450335, but forgot to re-raise it directly prior to the PR being merged.
N/A
N/A
> chore: Correct o-autocomplete comment

- components/o-expander/src/tsx/expander.tsx
This PR resolves a bug related to displaying `[object object]` on the `o-expander` storybook example.
[OR-632](https://financialtimes.atlassian.net/browse/OR-623)
[OR-632]: https://financialtimes.atlassian.net/browse/OR-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix bug in expander tsx template

- components/o-overlay/src/js/overlay.js
[As MDN explains](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal), non-modal dialogs (which o-overlay creates when the 'modal' option is set to false) shouldn't have `aria-modal=true`.
> Set aria-modal according to `opts.modal` (o-overlay)

- apps/for-everyone-website/src/components/ButtonPreview.astro
- apps/for-everyone-website/src/content-partial/docs/components/buttons-behaviour.mdx
- apps/for-everyone-website/src/content-partial/docs/components/buttons-guidelines.mdx
- apps/for-everyone-website/src/content/docs/components/buttons.mdx
- apps/for-everyone-website/src/content/docs/internal/components/buttons.mdx
- apps/for-everyone-website/src/content/docs/professional/components/buttons.mdx
- apps/for-everyone-website/src/content/docs/sustainable-views/components/buttons.mdx
- components/o3-button/README.md
- components/o3-button/main.css
- components/o3-button/src/tsx/button.tsx
- components/o3-button/src/types/index.ts
I have abstracted the "Preview" component out. It still needs work, but is better.
> docs: Add fluid button documentation

- components/o3-tooltip/main.css
- components/o3-tooltip/src/ts/tooltip.ts
add extra padding for the title so it does not obscure close button
[OR-653](https://financialtimes.atlassian.net/browse/OR-653)
[OR-653]: https://financialtimes.atlassian.net/browse/OR-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix overlapping header on cross icon

- components/o-autocomplete/README.md
- components/o-autocomplete/demos/src/dynamic-custom-highlighted-suggestion/data.js
- components/o-autocomplete/demos/src/dynamic-custom-highlighted-suggestion/dynamic-custom-highlighted-suggestion.js
- components/o-autocomplete/demos/src/dynamic-custom-highlighted-suggestion/dynamic-custom-highlighted-suggestion.mustache
- components/o-autocomplete/origami.json
- components/o-autocomplete/package.json
- components/o-autocomplete/src/js/autocomplete.js
- package-lock.json
This PR makes changes which extend on those introduced by https://github.com/Financial-Times/origami/pull/1127 and enables highlighting of custom rendering of suggestions.
If the user does not provide a `suggestionTemplate` in the options when instantiating an instance of `oAutocomplete` then the `Autocomplete.suggestionTemplate` will be used:
https://github.com/Financial-Times/origami/blob/f11860c20b67a7584d8b04f1948ff54dcb90d68d/components/o-autocomplete/src/js/autocomplete.js#L387-L413
This has a direct reference to `autocompleteEl` (via `this.autocompleteEl`), which can be used to acquire the current text input value, which is then used to enable highlighting of the suggestion.
However, when providing a custom `suggestionTemplate` function, this direct reference to `autocompleteEl` is …
> feat: Add query parameter to custom suggestionTemplate function

- .github/workflows/chromatic.yml
- components/o3-typography/body.css
- components/o3-typography/src/tsx/body.tsx
- components/o3-typography/stories/core/body.stories.tsx
- components/o3-typography/stories/core/professional/body.stories.tsx
- components/o3-typography/stories/story-templates.tsx
* introduce O3 Typography Body small.
* remove duplicated argtypes from O3 Typography Body stories.
* Align O3 Typography Body sizing to what is used in design.
[OR-556](https://financialtimes.atlassian.net/browse/OR-556?atlOrigin=eyJpIjoiOWI3YjFmYzhkMzY5NGMxYWJmOWRlZGJlNWU5Nzc0ZmQiLCJwIjoiaiJ9)
[OR-556]: https://financialtimes.atlassian.net/browse/OR-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OR-556: introduce body small

- components/o-buttons/stories/button.scss
- components/o-editorial-layout/stories/core/editorialLayout.scss
- components/o-expander/stories/expander.scss
- components/o-ft-affiliate-ribbon/stories/ft-affiliate-ribbon.scss
- components/o-icons/stories/icons.scss
- components/o-loading/stories/loading.scss
- components/o-quote/stories/quote.scss
- components/o-share/stories/share.scss
- components/o-social-follow/stories/social-follow.scss
- components/o-stepped-progress/stories/stepped-progress.scss
We inconsistently include o-normalise and o-fonts CSS within o2 Storybook demos. If we first visit a story which does, other stories look okay. If however the first story we visit doesn't include o-normalise or o-fonts, we get a borked component demo which doesn't accurately reflect what it should look like.
```
for i in (rg oNormalise ./components/**/stories/**/**.scss --files-without-match);
echo -e "@import '@financial-times/o-fonts/main';\n@import '@financial-times/o-normalise/main';\n@include oFonts();\n@include oNormalise();\n\n$(cat $i)" > $i;
end;
```
> docs: include fonts in o2 storybook demos

- components/o3-typography/package.json
> fix: remove type: module from o3-typography package

- apps/for-everyone-website/README.md
- apps/for-everyone-website/astro.config.mjs
- apps/for-everyone-website/src/content/docs/about/faq.md
- apps/for-everyone-website/src/content/docs/about/index.md
- apps/for-everyone-website/src/content/docs/index.mdx
We aim to move origami-for-everyone.ft.com (now origami-beta.ft.com) to origami.ft.com, moving away from Origami For Everyone. That project name means different things to different people and is no longer required.
> docs: origami for nobody

- apps/for-everyone-website/src/components/TypeScale.astro
- components/o3-foundation/fonts.css
- components/o3-foundation/src/css/brands/core.css
- components/o3-foundation/src/css/brands/sustainable-views.css
1. Set format to `woff2-variations`, to indicate we are using a VF.
2. Do not use CSS Custom Property in `@font-face`, it is not supported.
3. Set `font-weight` range in `@font-face`. A list of values is invalid.
> fix: Correct font weight in Safari

- components/o-tooltip/src/js/tooltip.js
- components/o-tooltip/test/Tooltip.test.js
- package-lock.json
This PR allows o-tooltip to receive a HTMLElement instead of an ID string, allowing for the usage patterns identified in the linked issue.
#1609
> feat: o-tooltip opts.target can be HTMLElement

- libraries/o-tracking/src/javascript/core/session.js
- libraries/o-tracking/test/core/session.test.js
Change the behavior of current internal session tracking to actually generate a new session and set the `isNew` flag whenever the current one expires.
[DATA-9210](https://financialtimes.atlassian.net/browse/DATA-9210)
[DATA-9210]: https://financialtimes.atlassian.net/browse/DATA-9210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix new session behavior for o-tracking

- libraries/o-tracking/src/javascript/tracking.js
Update the internal version of o-tracking
> backstage: bump o-tracking internal version

- components/o-video/README.md
- components/o-video/src/js/video.js
This PR allows the targeting property of the Video class to be passed in as an option when creating new o-video instances. currently when attempting to modify the targeting object in an instance class it requires two steps, creating a new instance variable and then accessing the targeting object on this variable. This change will allow for single step changes to be made when attempting to modify the properties of the targeting object. see (https://github.com/Financial-Times/next-article/pull/5507)
https://financialtimes.atlassian.net/browse/ADSDEV-1830
> fix: allow targeting to be passed as an option in o-video instances

- components/o3-typography/body.css
- components/o3-typography/caption.css
- components/o3-typography/footer.css
- components/o3-typography/heading.css
- components/o3-typography/link.css
- components/o3-typography/list.css
> fix: target o3-typography wrapper descendants with direct 

- release-please-config.json
- scripts/regenerate-ci-config-files.js
https://github.com/googleapis/release-please/blob/cb106cd0b5ae5c3e2a3b015487dc615eba72b842/docs/manifest-releaser.md?plain=1#L134
Last time I regenerated from a template and enabled auto merge, resulting in 0 changes.
https://github.com/Financial-Times/origami/pull/1637/files
> chore: Attempt to make release-please ignore the last bad release commit

- components/o-multi-select/src/js/multi-select-options.js
Removed trim from the optionEl.textContent and added it to the button.textContent line.
Jira [ticket](https://financialtimes.atlassian.net/browse/SP-3623)
> Fix: moved trim from textContext label and onto the button

- README.md
Add link to origami for everyone astro website. Because I keep forgetting it.
> docs: add link to origami for nobody

- components/o3-button/main.css
Before / After:
Small, icon only button now aligns with our designs:
- Square
- 20px icon
> fix: small button icon size and icon-only ratio (square)

- components/o-header/MIGRATION.md
- components/o-header/src/scss/features/_top.scss
- components/o-header/src/tsx/Props.ts
- components/o-header/src/tsx/header-default.tsx
- components/o-header/src/tsx/sticky.tsx
- components/o-header/src/tsx/top.tsx
- components/o-header/stories/storybook-data/index.ts
- components/o-header/stories/storybook-data/navbarTopRight.ts
- components/o-header/stories/storybook-data/navbarTopRightAnon.ts
- components/o-header/stories/storybook-data/profile.ts
Roll out the variant of the `experimentalAccountEntryTest` AB test as the default permanent behaviour
In early 2024 the Retention team ran an AB test to try and improve the user experience of the header by trying to reduce confusion of the difference between Settings & Account and myFT. This test was successful so we are now rolling these changes out to all users. The changes that are relevant to this PR are
1. Add styling for the new My Account / Sign in link
2. Rename `Settings & Account` to `My Account`
3. Rename `myFT` to `myFT Feed`
4. Move My Account to the top right slot, replacing the myFT logo
5. Move myFT to the bottom right slot, replacing the old Settings & Account link
**Anonymous user - Previous layout**
**Anonymous user - New layout**  
**Signed in user - Previous layout** …
> Header myaccount updates

- components/o3-foundation/focus.css
Add some point the token `o3-focus-use-case-outline-color` was updated to represent a box shadow and not a colour. It would be a breaking change to rename without mapping. This PR uses the value as a shadow rather than outline colour.
> fix: Fix link focus rings [OR-702]

- components/o-icons/README.md
Links inside o-icons readme were still pointing to registry. These have now been updated to point to Storybook.
> docs: replace registry links

- apps/for-everyone-website/src/pages/[brand]/blog.astro
- apps/for-everyone-website/src/pages/blog/index.astro
Ensure the currently selected brand is maintained when viewing the blog index page.
This allows the user to navigate between branded and non-branded blog content.
> docs: Brand the blog index page [OR-714]

- apps/for-everyone-website/package.json
- apps/for-everyone-website/remove-branded-headings.mjs
- package-lock.json
- patches/@astrojs+starlight+0.23.2.patch
> Prerequisites to reduce duplicate content

- components/o-comments/src/js/stream.js
- components/o-comments/src/js/utils/auth.js
- components/o-comments/src/scss/coral-talk-iframe/main.scss
- components/o-comments/test/helpers/fixtures.js
- components/o-comments/test/methods/stream/authenticate-user.js
- components/o-comments/test/methods/stream/render-not-signed-in-message.js
- components/o-comments/test/stream.test.js
this PR is part of the work to **Stop registered and trial users to comment.** We will receive from next-comments-api new data that will tell if the user is anonymous, registered, trial or subscribed .
If the user is anonymous, registered or trial we will show them a a custom message , and the comment box ,guidelines and actions buttons over the comments will be hidden.
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-1493)
> feat: add feature onlySubscribers on comments

- components/o-comments/MIGRATION.md
- components/o-comments/README.md
- components/o-comments/package.json
- components/o-comments/src/js/stream.js
- package-lock.json
DSA compliance.
The Coral link to report illegal comments works by reopening the same page in a new window, with some added query string items. However, if someone is a first-click free user this will result in the barrier page loading instead. This means that anonymous users can't use the tool to report illegal comments, which is a condition of the DSA.
This change intercepts the clicks on this link, alters the path to a route that is not behind the paywall, then opens that url in a new window.
https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?assignee=5be57e310e625003a46e9693&selectedIssue=CI-2234
N/A
> fix!: ci-2234 coral illegal comments url

- components/o-comments/package.json
- package-lock.json
Sets ftdomdelegate back to v5.0.0 due to publishing issues with 5.0.1
> fix: use published ftdomdelegate version

- components/o-comments/README.md
- components/o-comments/src/js/comments.js
- components/o-comments/src/js/count.js
- components/o-comments/src/js/stream.js
- components/o-comments/src/js/utils/auth.js
- components/o-comments/src/js/utils/display-name.js
- components/o-comments/src/js/utils/purge-jwt-cache.js
- components/o-comments/test/count.test.js
Add options commentsAPIUrl and commentsAuthUrl to o-comments
commentsAPIUrl sets the host url when making requests to comments API
commentsAuthUrl sets the entire url when making request to comments API just for authentication
These properties will be used as for testing and QA purposes
> feat: add options commentsAuthUrl and commentsAPIUrl to o-comments

- apps/for-everyone-website/src/components/editorial-typography/BodyStyles.astro
The styles aren’t applying (this only impacts the preview, since we use private tokens so to replicate styles and show per breakpoint). The M variant does not exist
> docs: correct editorial body style preview [OR-729]

- apps/for-everyone-website/astro.config.mjs
- apps/for-everyone-website/src/components/ContentPanel.astro
- apps/for-everyone-website/src/components/editorial-typography/DropCap.astro
- apps/for-everyone-website/src/components/editorial-typography/preview/DropCap.tsx
- apps/for-everyone-website/src/content/docs/guides/typography.mdx
This shows the drop cap and summary, which are not yet used by any brands but will be for future Specialist Titles.
More work is required (in a future pr) including checking links to figma & storybook – some are set, some aren't. This may benefit from dedicated time to make Figma/Storybook links easier to define and manage – could we define a Figma location once for Storybook's panel and the site?
> docs: Add basic whitelabel support to the website [OR-731]

- apps/dictionary/tokens/whitelabel/components/o3-editorial-typography.json
- apps/for-everyone-website/astro.config.mjs
- apps/for-everyone-website/src/components/ContentPanel.astro
- apps/for-everyone-website/src/components/editorial-typography/DropCap.astro
- apps/for-everyone-website/src/components/editorial-typography/preview/DropCap.tsx
- apps/for-everyone-website/src/content/docs/guides/typography.mdx
- components/o3-editorial-typography/README.md
- components/o3-editorial-typography/drop-cap.css
- components/o3-editorial-typography/src/css/brands/whitelabel.css
- components/o3-editorial-typography/src/css/tokens/whitelabel/o3-editorial-typography/_variables.css
- components/o3-editorial-typography/src/tsx/body.tsx
- components/o3-editorial-typography/src/tsx/index.ts
- components/o3-editorial-typography/src/tsx/summary.tsx
- components/o3-editorial-typography/src/types/index.ts
- components/o3-editorial-typography/stories/core/body.stories.tsx
- components/o3-editorial-typography/stories/story-templates.tsx
- components/o3-editorial-typography/stories/whitelable/big-number.stories.tsx
- components/o3-editorial-typography/stories/whitelable/body.stories.tsx
- components/o3-editorial-typography/stories/whitelable/byline.stories.tsx
- components/o3-editorial-typography/stories/whitelable/caption.stories.tsx
- components/o3-editorial-typography/stories/whitelable/headline.stories.tsx
- components/o3-editorial-typography/stories/whitelable/link.stories.tsx
- components/o3-editorial-typography/stories/whitelable/list.stories.tsx
- components/o3-editorial-typography/stories/whitelable/pull-quote.stories.tsx
- components/o3-editorial-typography/stories/whitelable/standfirst.stories.tsx
- components/o3-editorial-typography/stories/whitelable/summary.stories.tsx
- components/o3-editorial-typography/stories/whitelable/topic-tag.stories.tsx
- components/o3-editorial-typography/summary.css
These are specific to the whitelabel brand for now. We intend to roll them out to future Specialist Brands.
**Summary:**
**Drop cap**: Where body copy is "Tt...[lorem ipsum]" the "T" is the dropcap and the top of the "T" aligns with the top of "t" and the button of "T" aligns with the baseline of the 3rd line of copy.
> Implement drop cap and summary [OR-725]

- components/o3-button/main.css
- package-lock.json
When a button is clicked (pressed) the focus state is applied until clicking elsewhere. Avoid this by applying focus colours with `:focus-visible`.
I chose not to add a `:focus` fallback as:
- Support for `:focus-visible` is very good now.
- We still have a `:focus` ring.
> fix: Apply button focus colours on `:focus-visible` only.

- apps/for-everyone-website/src/components/editorial-typography/DropCap.astro
- apps/for-everyone-website/src/content/docs/guides/typography.mdx
- components/o3-editorial-typography/drop-cap.css
- package-lock.json
And correct whitelabel link to Storybook
> docs: show whitelabel editorial typography

- components/o-comments/src/js/comments.js
Fix options initialisation along with data-attributes
We were choosing between options or data-attributes instead of overriding and assigning on top of each other.
So the preference now is options passed programmatically have preference over data-attributes and overrides values got from it but don't remove the values of other options assign by data-attributes
> fix: fix assign of options in conjunction with data-atributtes

- components/o-comments/src/js/stream.js
- components/o-comments/src/js/utils/auth.js
Add tracking and allow to pass links to subscribe and login. In case we don't pass that property the text will be shown without links
[ticket](https://financialtimes.atlassian.net/browse/CI-1493)
> feat: add tracking and optional links for subscribe link and login link

- components/ft-concept-button/main.scss
- components/ft-concept-button/src/tsx/concept-button.tsx
Add FT Professional themes to `ft-concept-button`
https://www.figma.com/design/MyHQ1qdwYyek5IBdhEEaND/%F0%9F%92%A0-FT-UI-Library---Origami-(o2)?node-id=0-915&t=AAqSgW1l8rOOOG7E-0
> feat: add professional-inverse theme to ft-concept-button

- components/o-header/src/scss/features/_search.scss
we previously try to fix the search bar wide and we add the max-width to the input instead the form that causes the typeahead size not be the same because is absolute positioned and is looking for the width of the nearest parent so we need to apply to max-width to the correct element
https://github.com/Financial-Times/origami/pull/1740/files
**ScreenShots**
Before:
After:
> feat: fix search term wide

- components/o-comments/src/js/stream.js
Fix typos on comments barrier message according to discussion on this [ticket](https://financialtimes.atlassian.net/browse/CI-1493?focusedCommentId=836837)
> fix: fix typos on comments barrier message

- components/o-comments/src/js/stream.js
Fix typos according to this [ticket](https://financialtimes.atlassian.net/browse/CI-1493?focusedCommentId=836927)
Sentences to fix:
"Commenting is only available to readers with an FT subscription"
"You are still on a trial period"
> fix: fix typos

- components/o-video/src/js/ads.js
This PR changes the scp attribute on search params for video ads requests to not use encodeURI, which was causing a wrong encoding on the browser and impacting the Commercial team that are no longer able to report on pos=video.
See the correct behaviour:
Instead of the correct behavior above, we're getting `scp=pos%253Dvideo%2526ttid%253D1eeebd90-25d4-4421-a175-deedcdbf9c18`, where the `%25` char is being added incorrectly.
https://financialtimes.atlassian.net/browse/ADSDEV-1952
> fix: pos=video issue whereby commercial are unable to report

- components/o-colors/README.md
- components/o-colors/src/scss/_palette.scss
- components/o-colors/src/scss/_use-cases.scss
Including a new `wheat-subtle` color in the palette file to be used primarily as a background color for ad slots.
https://financialtimes.atlassian.net/browse/ADSDEV-1961
> feat: new color to attend ad slots

- components/o3-tooltip/main.css
This removes excess space below the toggle tip and allows it to be positioned correctly in flow.
It will then be possible to remove these overrides with a couple extra steps for the product. Remove the `div` with the brand attribute, and apply it to an existing parent element. Use the `gap` property and o3 CSS Custom Properties for spacing on the partner content title element:
https://github.com/Financial-Times/next-article/blob/5c2eb8785dfcf7e11341dec1d6d9b5c4395658ae/client/partner-content.scss#L164 
Before: 
After:
> fix: Make the toggle tip component inline.

- README.md
- Updated the root README to include commands for running Storybook for Origami's o3 components and the Origami Design System website
> docs: Add storybook commands for o3 and apps/for-everyone-website 

- components/o-header/MIGRATION.md
- components/o-header/src/scss/_variables.scss
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_search.scss
- components/o-header/src/scss/features/_top.scss
- components/o-header/src/tsx/drawer.tsx
- components/o-header/src/tsx/search.tsx
- components/o-header/src/tsx/sticky.tsx
_Please, follow my commit history while reviewing the PR._ 
FT header is undergoing designs changes as a part of the initiative to revamp search on ft.com.
**Main changes:**
* search input field has a `type="search"` which is the semantically correct type. We are getting some built-in advantages of using `type="search"`. It should have a positive effect on `a11ty`. [More about it](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search) 
* search form and search button are bigger
* search container overlays the rest of the nav menu and rest of the content
* magnifying glass icon is shown on the tablet break-point
* drawer search is hidden on the tablet break-point
* close button is changed from `x` to `close`
<details>
<summary>
Desktop
</summary>
</details>
<details> …
> The new `o-header`

- components/o-header/MIGRATION.md
- components/o-header/src/scss/_brand.scss
- components/o-header/src/scss/_mixins.scss
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_top.scss
- components/o-header/src/tsx/Props.ts
- components/o-header/src/tsx/components/ask-ft-button.tsx
- components/o-header/src/tsx/drawer.tsx
- components/o-header/src/tsx/header-default.tsx
- components/o-header/src/tsx/header.tsx
- components/o-header/src/tsx/sticky.tsx
- components/o-header/src/tsx/top.tsx
- components/o-header/stories/arg-types.ts
- components/o-header/stories/header.stories.tsx
- Add ASK FT button linking to `https://ask.ft.com/` in `o-header`:
- Top header - visible on screen size L and up
- Drawer - visible on smaller screens, same as search in the drawer
- Sticky header - visible on screen size L and up
- Add new optional `showAskButton` prop in `THeaderOptions` to control ASK FT button rendering. By default, the button is not rendered
- Add `showAskButton` prop in `o-header` stories
Ask FT button was previously added in `dotcom-ui-header` and it is currently active on ft.com home and article pages. This PR adds the same in `o-header` and will be followed with `dotcom-ui-header` changed to align with `o-header`. For reference - this is the PR in `dotcom-ui-header` which has added the button there - https://github.com/Financial-Times/dotcom-page-kit/pull/1031 …
> Add Ask FT button to o-header

- components/o3-foundation/README.md
- components/o3-foundation/grid.css
- components/o3-foundation/stories/grid-sb-styles.css
- components/o3-foundation/stories/grid.tsx
Some components outside of grids may use grid dimensions. For example, form elements may use `max-width` constrained by a number of columns in grid, without being part of one.
This PR adds CSS custom properties at each breakpoint to give components outside of a grid some values to work with.
> feat: introduce `o3-grid-column-width` CSS Custom Property

- components/o3-foundation/normalise.css
The `prefers-reduced-motion` setting is binary and does not give users much control or choice. Preferring reduced motion does not mean the user wants no animation or transition at all. It should be used on a case by case basis. For example to stop the largest and most potentially problematic cases (e.g. parallax). By defaulting to to no animation or transition with `!important` we make it difficult to undo.
```css
/* Reduce motion */
@media (prefers-reduced-motion: reduce) {
*,
*:before,
*:after {
animation-duration: 0.001s !important; /* stylelint-disable-line declaration-no-important */
transition-duration: 0.001s !important; /* stylelint-disable-line declaration-no-important */
animation-iteration-count: 1 !important; /* stylelint-disable-line declaration-no-important */
}
}
``` …
> fix: Remove prefers-reduced-motion from normalise.css

- components/o-header/src/scss/_base.scss
- components/o-header/src/scss/features/_drawer.scss
| Before | After |
|--------|-------|
| https://github.com/user-attachments/assets/328ff53b-c11b-4ca4-8486-3eb240358af7 | https://github.com/user-attachments/assets/a58eafac-a2d9-4057-8ef6-4139a2c70ab1 |
More about [over-scrolling](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior)
Just a note on this, on mobile it will have a bigger effect and it will disable bouncing scroll behaviour, which I think is an improvement. Mobile drawer should be more constrained.
> In some cases, these behaviors are not desirable. You can use overscroll-behavior to get rid of unwanted scroll chaining and the browser's Facebook/Twitter app-inspired "pull to refresh"-type behavior.
https://github.com/user-attachments/assets/232476d8-4172-467c-a5c1-1a8e19564269
The overscrolling issue is also …
> [CON-3537] o-header tweaks

- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_search.scss
- components/o-header/src/tsx/drawer.tsx
We need to make some design adjustments that we saw after release new version of search drawer
Changes:
- Padding between the search bar and the “Top sections” box should be 16px. If there’s an “ask FT” button, then it should be 16px between the bar and the button and 16px between the button and the “Top sections”
- Text inside the bar seems very faint so we use black tint 60 (happens in safari)
- The underline on the option that’s not selected should be black tints 80, not teal (happens in safari)
https://financialtimes.atlassian.net/browse/CON-3544
https://docs.google.com/document/d/1qsmZwl4AREo__B46fivT5MHLc90lmClil_XBPH0DYw4/edit
- [ x] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in …
> fix: align padding in drawer

- .github/workflows/chromatic.yml
Changes to the way `storybookBaseDir` should mean that we should no longer need to set this according to [this](https://github.com/chromaui/chromatic-cli/issues/1027)
> backstage: remove storybook base dir

- components/o-header/src/scss/_variables.scss
Increasing `z-index` for nav items to win `z-index` wars.
| Before | After |
|--------|-------|
| ![image](https://github.com/user-attachments/assets/1c865e22-1b10-4d72-ab27-d8561dbc55a7) | ![image](https://github.com/user-attachments/assets/50a70d89-e1b9-4280-9932-5ed3dd134e68) |
> fix: (o-header) increase the value of o-header-mega to 5

- components/o-header/src/js/subnav.js
When building a new Life & Arts navigation for the FT App, we spotted that the o-header sub navigation does not scroll to the correct position of the selected item. This can be seen on Ft.com also when on a smaller viewports (390 width) on here as an example: https://www.ft.com/globetrotter/miami.
There is a bug in the way we calculate how far to scroll in order to make sure the selected item is in view in the SubNav.
We were previously calculating the scroll position by first checking how far off the item is out of view via `currentSelectionEnd - wrapperWidth`. If this was less than the wrapper width, we would only scroll by half the width of the wrapper, which is not the right thing to do here especially when the item is only slightly out of view.
The fix includes:
* Removing the …
> fix: (o-header) subnav scroll behaviour

- components/o3-foundation/README.md
- components/o3-foundation/main.css
- components/o3-foundation/src/css/components/z-index.css
To remove [nUiZIndexFor](https://github.com/Financial-Times/n-ui-foundations/blob/3bb178d96bc4873514a2d48ca4df8453c17b29a6/util/_mixins.scss#L21) we would like Origami guidance on `z-index`.
> feat: add z-index values to o3

- components/o3-social-sign-in/package.json
o3-social-sign in has a tokens build step in it's `build` script, there are no tokens in this package so it can be removed.
This will help clean up local dev by reducing the generation of unnecessary files.
> fix: remove unnecessary token building for o3-social-sign-in

- .prettierignore
Tokens Studio does some formatting on push, which can be overridden by prettier in local dev setups. This is adding noise to PRs. Ignoring tokens should reduce noice in PRs in future.
> backstage: ignore tokens in prettier

- components/o3-form/src/css/components/text-input.css
The text input field has padding of `16px` either side, this makes the total width of the field exceed the `max-width` defined by `--o3-grid-columns-to-span-width`.
Using `box-sizing: border-box` should ensure that the `max-width` takes into account padding.
> fix: size text input with border-box

- components/o-header/README.md
- components/o-header/src/scss/_mixins.scss
- components/o-header/src/scss/features/_nav.scss
- components/o-header/src/scss/features/_subnav.scss
The App has a requirement to have a sub navigation where link items have 'primary' styles and are capitalised with font weight 600. Currently, the `.o-header__nav-link--primary` class provides these styles for primary navigation links, but no equivalent modifier exists for the sub navigation `.o-header__subnav-link`.
~~To address this, this introduces `.o-header__subnav-link--primary` style modifier for the sub navigation. Additionally, the shared styles are now extracted into a reusable mixin.~~
Now updated to apply the modifier class directly to `.o-header__subnav--primary` instead of individually to the child item links. This also includes background colour update to use `paper` colour so it is styled more like the main navigation. 
Jira ticket: …
> feat: o-header subnav primary link styles

- libraries/o-tracking/package.json
- libraries/o-tracking/src/javascript/core.js
- libraries/o-tracking/src/javascript/core/session.js
- libraries/o-tracking/src/javascript/tracking.js
- libraries/o-tracking/src/javascript/utils.js
- libraries/o-tracking/test/core.test.js
- libraries/o-tracking/test/core/session.test.js
- Added a new property `timestamp` to the session object.
- Added a new logging utility function for dev with namespacing support
[DATA-9749](https://financialtimes.atlassian.net/browse/DATA-9749)
[DATA-9749]: https://financialtimes.atlassian.net/browse/DATA-9749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add timestamp to session generations in o-tracking

- components/o-private-foundation/main.scss
- components/o-private-foundation/src/scss/o-buttons/main.scss
- components/o-table/demos/src/demo.scss
- components/o-table/main.scss
- components/o-table/package.json
- components/o-table/src/js/Tables/OverflowTable.js
- components/o-table/src/scss/_responsive-overflow.scss
- package-lock.json
Takes o3-button and refactors to work in an o2 world. Slightly
odd use of Sass/CSS Custom Properties, with Sass conditionals
used to output duplicate CSS Custom Properties which override
each other in the same declaration. This was the safest way
to reuse o3 styles by effectively replacing class names for
Sass if statements. It's also more readable and simple than o2
Sass. Despite duplicating some properties, CSS output and
performance will be improved by moving away from the Origami
Image Service for coloured icons.
Currently supports:
- Types
- Themes
- Sizes
- Icons
- Icons only
Does not yet support:
- Custom theme maps
Will not support:
- Outputting CSS granularly. There are not many buttons left in
o2 components, and bundle size is reduced overall as noted above.
Other things of …
> Replace o-buttons with o-private-foundation in o-table [OR-1051]

- libraries/o-tracking/src/javascript/core/send.js
- libraries/o-tracking/src/javascript/core/store.js
- libraries/o-tracking/src/javascript/tracking.js
- libraries/o-tracking/src/javascript/utils.js
- libraries/o-tracking/test/core/send.test.js
- libraries/o-tracking/test/core/store.test.js
- libraries/o-tracking/test/events/custom.test.js
- libraries/o-tracking/test/utils.test.js
[This conversation](https://financialtimes.slack.com/archives/C07U72QTQCA/p1730548886171719?thread_ts=1730484139.054259&cid=C07U72QTQCA) uncovered an issue whereby multiple offline calls to `track()` could potentially share object references (for example, in the additional `context` object).
The previous `containsCircularPaths()` implementation wasn't really looking for **circular** paths, but rather multiple references to the same object. See the [original PR](https://github.com/Financial-Times/o-tracking/pull/263) and [issue](https://github.com/Financial-Times/o-tracking/issues/115).
A use-case which is common in an offline-first application such as FT App - queueing multiple events to be stored and sent when next online - is somewhat likely to include a shared reference across the …
> fix: Correctly detect truly circular paths in JS objects, rather than objects with multiple references

- apps/dictionary/src/transforms/private-prefix.js
- apps/dictionary/tokens/$themes.json
We do not want to export our typography scale in Figma for end users, as we have specific usecases now. It is a bit of a pain to exclude the generated Figma variables or styles from publihsing. To support migration efforts we want it to still be available in the engineering token set.
I have rebuilt tokens and there are no changes to the built CSS, which we expect.
> chore: Make base type tokens tokens.

- components/o-header/main.scss
- components/o-header/src/scss/_mixins.scss
- components/o-header/src/scss/features/_drawer.scss
- components/o-header/src/scss/features/_search.scss
- components/o-header/src/scss/features/_transparent.scss
> fix: restore o-header buttons to design

- libraries/math/package.json
- libraries/math/test/index.test.js
- libraries/sass-mq/package.json
- libraries/sass-mq/scripts/test.sh
- libraries/sass-mq/test/eyeglass-test.js
- package-lock.json
- package.json
Currently the mono-repo needs `node-sass` which is deprecated, for tests. This particular dependency requires you to have python installed on the machine to do… JavaScript things.
N/A - adhoc
N/A
> chore: testing this out without node sass

- components/o3-editorial-typography/details.css
- components/o3-editorial-typography/heading.css
- components/o3-editorial-typography/stories/story-templates.tsx
Builds on #1923 with:
* Remaining heading tokens
* Quote tokens
Note that `o3-editorial-typography-pullquote-content` tokens have the wrong values – this needs to be updated in Token Studio and applied in Figma. Feedback left for the design team. Moving on for now.
> Begin applying use-case tokens to o3 components. 

- components/o-colors/test/scss/_functions.test.scss
- components/o-colors/test/scss/_mixins.test.scss
Testing the colours in `o-colors` now isn't being matched with hex codes, but rather rgb values with decimals which makes it even more specific and is a new standard that was recommended in February 2024 - See https://www.w3.org/TR/css-color-4/.
As a subsequent reaction, it was failing tests so this is just updating them to use rgb values with decimals. Colour me surprised, it all passed tests locally and on GitHub Actions too!
[OR-1207](https://financialtimes.atlassian.net/browse/OR-1207)
N/A
[OR-1207]: https://financialtimes.atlassian.net/browse/OR-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: change from hex to rgb in tests

- components/o-visual-effects/test/scss/_mixins.test.scss
With the recommendation to use decimal points in rgb colours from W3.org. See https://www.w3.org/TR/css-color-4/ for further context. It makes sense to update the tests to use rgb with decimal points from this point onwards.
Yes, it's just one test being updated. :)
[OR-1220](https://financialtimes.atlassian.net/browse/OR-1220)
N/A
[OR-1220]: https://financialtimes.atlassian.net/browse/OR-1220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OR-1220]: Fix failing test for o-visual-effects

- components/o-typography/test/scss/_mixins.test.scss
Updating the tests in `o-typography` to use rgb with decimal values. See [W3.org/TR/css-color-4](https://www.w3.org/TR/css-color-4/) for the rationale and a little bit of future proofing.
[OR-1219](https://financialtimes.atlassian.net/browse/OR-1219)
N/A
[OR-1219]: https://financialtimes.atlassian.net/browse/OR-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OR-1219]: Fix failing tests on o-typography

- components/o3-form/src/css/components/checkbox.css
- components/o3-form/src/css/components/error-summary.css
- components/o3-form/src/css/components/feedback.css
- components/o3-form/src/css/components/form-field.css
- components/o3-form/src/css/components/password-input.css
- components/o3-form/src/css/components/radio-button.css
- components/o3-form/src/css/components/text-input.css
* Uses o3-typography's use case tokens in o3-form components.
* Removes unused class.
**note:** merge preserving commit history providing commits stay concise.
> or-1119: use typography use cases in o3-forms.

- components/o-message/main.scss
- components/o-message/src/scss/_mixins.scss
Uses the new typography use case tokens in o-message components
> feat: use typography use case tokens in o message

- components/o-forms/src/scss/_checkbox.scss
- components/o-forms/src/scss/_radio-box.scss
- components/o-forms/src/scss/_radio-round.scss
- components/o-forms/src/scss/shared/_base.scss
- components/o-forms/src/scss/shared/_brand.scss
- components/o-forms/src/scss/shared/_control-inputs.scss
- components/o-forms/src/scss/shared/_error-summary.scss
- components/o-forms/src/scss/shared/_single-inputs.scss
- components/o-forms/src/scss/shared/_validity.scss
Increase margin between form fields to accommodate larger error copy. Align colours to new o3-forms
> chore: Use standard type usecases within o-forms

- components/o-tooltip/main.scss
- components/o3-tooltip/main.css
Before / after. Within o-tooltip font size was previously inherited, and line height set very low:
> Apply type usecases to tooltip components [OR-1191]

- components/o-forms/demos/src/data/pa11y.json
- components/o-forms/demos/src/data/select.json
- components/o-forms/demos/src/data/text-input.json
- components/o-forms/demos/src/demo.scss
- components/o-forms/demos/src/interactive-suffix.mustache
- components/o-forms/demos/src/interactive.mustache
- components/o-forms/demos/src/inverse-form-whitelabel.mustache
- components/o-forms/demos/src/inverse-form.mustache
- components/o-forms/package.json
- components/o-forms/src/scss/_checkbox.scss
- components/o-forms/src/scss/_date.scss
- components/o-forms/src/scss/shared/_single-inputs.scss
- components/o-forms/stories/forms.scss
- components/o-forms/stories/select.stories.tsx
- components/o-forms/stories/textBox.stories.tsx
- components/o-forms/test/forms.test.js
- components/o-forms/test/helpers/fixtures.js
- components/o-message/main.scss
- components/o-message/src/scss/_mixins.scss
* Apply missing radius to o-forms checkbox.
* Correct o-forms date input width which is too small with larger text.
* Update o-forms demos / stories to show latest button design, since o-buttons will be deprecated.
* Correct token use in o-message since we deleted link tokens. I noticed the build failed.
Screenshots: https://financialtimes.slack.com/archives/G03ACR1MJ/p1737543643692009?thread_ts=1737455978.705169&cid=G03ACR1MJ
> o-forms corrections and o-message build error fix

- apps/for-everyone-website/src/content/docs/components/Form/password-input.mdx
- components/o-forms/main.scss
- components/o-forms/src/scss/modifiers/_inverse.scss
- components/o-forms/src/scss/shared/_base.scss
- components/o-forms/src/scss/shared/_brand.scss
- components/o3-form/src/css/components/checkbox.css
- components/o3-form/src/css/components/radio-button.css
- components/o3-form/src/tsx/PasswordInput.tsx
- Reduce checkbox / radio label type size to body base. We've already done this by accident in o-forms. Leave text input, etc, at `body-lg` by design.
- Correct tense in show password field.
> 2025 release forms design tweaks

- libraries/o-tracking/README.md
- libraries/o-tracking/src/javascript/events/component-view.js
I'm configuring the App Homepage `scrolldepth` tracking event using `oTracking.view.init()` in [this PR](https://github.com/Financial-Times/ft-app/pull/2878) by setting a selector that will trigger this event every time a `<section />` comes into the viewport. In the beginning, it was working as expected, but after some days I retested it and the `scrolldepth` events were not being sent as expected.
After some investigation, I realized that the problem was located in the **1.0** IntersectionObserver threshold defined [here](https://github.com/Financial-Times/origami/blob/4d2111699890b9cce57da3150401fbd722001773/libraries/o-tracking/src/javascript/events/component-view.js#L78). Looking [at the docs](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#threshold), this …
> o-tracking add IntersectionObserver.threshold as opt

- components/o-editorial-layout/MIGRATION.md
- components/o-editorial-layout/README.md
- components/o-editorial-layout/main.scss
- components/o-editorial-layout/package.json
- components/o-editorial-layout/src/scss/_mixins.scss
- components/o-editorial-layout/src/scss/_placeholders.scss
This allows o-editorial-typography to be deprecated. o-editorial-layout can continue to be used. It may or may not move to o3.
> chore: Remove o-editorial-typography from o-editorial-layout

- components/o-header/main.scss
- components/o-header/src/scss/features/_drawer.scss
- Where a px value was used directly, font size had visually increased due to Metric2
- Restores button radius for standalone buttons
**production / 2025-release currently (the problem)**
**now**
- Slightly larger copy inline with standard use-cases (16px, but with metric2).
- Note form placeholder text is massive. This is by design but this specific scenario could use a review. Out of scope for this PR.
> chore: Correct o-header font size

- components/o-footer/src/scss/_mixins.scss
- components/o-footer/src/scss/_variables.scss
When `$o-spacing-relative-units` is true, arrows were misaligned, due to borked calculations involving mixed px and rem values.
> fix: o-footer arrow position

- components/o-private-foundation/src/scss/o-normalise/_variables.scss
The inverse token was used for non-inverse focus state.
> chore: correct o2 focus ring [OR-1206]

- components/o-banner/src/scss/_mixins.scss
- components/o-banner/src/scss/layouts/_compact.scss
- components/o-banner/src/scss/layouts/_small.scss
There are a 1,000 variations of this one. Many are outmoded and it's often overridden with marketing customisations. That is to say, along with other on site messaging components in need of an audit and redesign! I'd love for them to come after forms this year.
In the meantime my approach to applying the new type use-cases has been to go up in size for headings.
This is a bit shouty but seems to keep the hierarchy better than using a lower weight title or body-lg. The "compact" variant becomes pretty redundant as we're normalising on a larger font size, so definitely a candidate for deprecation with a future audit. 
Screenshots / conversation:
https://financialtimes.slack.com/archives/C07GJU8UK7G/p1738152211384239
> banner type

- components/o-subs-card/demos/src/demo.scss
- components/o-subs-card/src/scss/_mixins.scss
- components/o-subs-card/src/scss/_themes.scss
* uses o-private-foundation/o-colors
* fixes a styling issue where primary button was used instead of secondary
> feat: use o-private-foundation/o-colors in o-subs-card

- components/o-colors/demos/src/color-mixer/color-mixer.scss
- components/o-colors/demos/src/contrast-checker/contrast-checker.scss
- components/o-colors/demos/src/demo.scss
- components/o-icons/stories/icons.scss
- components/o-typography/demos/src/demo.scss
- components/o-typography/main.scss
- components/o-typography/package.json
- components/o-typography/src/scss/_brand.scss
- components/o-typography/src/scss/_mixins.scss
- components/o-typography/src/scss/use-cases/_general.scss
- components/o-typography/stories/typography.scss
- components/o-visual-effects/stories/visual-effects.scss
Reverts changes in deprecated components:
* o-typography
* o-visual-effects
Reverts linting changes by components unaffected by migration, this is to save releasing them as a big release:
* o-colors
* o-icons
* o-spacing
> fix: revert changes to components not being upgraded

- components/o3-foundation/README.md
- components/o3-foundation/src/css/components/typography/index.css
* Removes `o3-typography-bold` and `o3-typography-italic` classes.
Releasing as minor as there are no usages outside of Origami. Verified with github search.
Docs appear to be updated already. [Readme](https://github.com/Financial-Times/origami/tree/2025-release/components/o3-foundation), [Migration]()
> feat: remove bold and italic o3-typography classes

- components/o-normalise/src/scss/_mixins.scss
Reverts usage of o3 colour tokens in o-normalise. To fix build issues on `2025-release`.
> fix: revert o3 o normalise changes

- components/o-private-foundation/src/scss/o-typography/main.scss
Sass was stripping the `" "` needed for the `font-family` property to have `"metric 2 VF"`. Removed the `#{}` from the Sass file affected so that it wouldn't strip the double quotes out when the Sass got compiled into CSS.
[OR-1350](https://financialtimes.atlassian.net/browse/OR-1350)
N/A
[OR-1350]: https://financialtimes.atlassian.net/browse/OR-1350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove Sass interpolation #{} from font-family [OR-1350]

- components/o3-editorial-typography/details.css
Aligns weight of block quote author to original style before `2025-release` was merged.
> fix: use correct weight on block quote author

- components/o3-editorial-typography/list.css
Fixes an issue where unordered list bullets would not match the colour of the text on inverse themes.
> fix: use same colour on editorial typography bullets as text

- components/o3-foundation/src/css/components/typography/caption.css
- components/o3-foundation/src/css/components/typography/index.css
- components/o3-foundation/src/css/components/typography/usecases.css
- components/o3-foundation/stories/story-templates.tsx
…wrapper
`o3-typography-caption` was replaced with `o3-type-detail`, the former classes have been removed to reflect this.
* removes `o3-typography-caption` classes
* ensures inverse colours apply correctly for `o3-type-detail` and `figcaption` elements in wrapper
> chore: apply inverse styles to caption, remove caption classes

- libraries/o-brand/README.md
This triggers a release, added in a previous commit.
> fix: Add oBrandGetCurrent to return the current brand

- components/o-header/main.scss
- components/o-header/src/scss/features/_search.scss
* Introduces rounding to search and subscribe buttons.
> fix: round non-navigational buttons on o-header

- components/o-private-foundation/src/scss/o-typography/main.scss
o-colors was used in o-private-foundation, these have been replaced with `oPrivateColors` functions.
> fix: remove o-colors usages in o-private-foundation

- components/o3-button/main.css
- components/o3-button/stories/story-templates.tsx
Storybook was applying `disabled` attribute to LinkButton which uses an anchor tag, `disabled` is not a valid attribute on anchors, instead use `aria-disabled`
> fix: use aria-disabled on LinkButton

- components/o3-editorial-typography/README.md
- components/o3-editorial-typography/details.css
- components/o3-editorial-typography/stories/story-templates.tsx
This has the potential to be a visually breaking change where `o3-editorial-typography-byline-location` is used outside of `o3-editorial-typography-byline`. We're happy with that given what we know about `o3-editorial-typography` use, vs. keeping that class around deprecated.
From Kara:
if we look at the example in the docs, "Joe Doe in London", it's marked up with Joe Doe as author and in London as location. but not all the text in the byline that isn't an author is a location, you can have bylines that are like "Dan McCrum in London and Antoine Gara in New York", where the "and" isn't part of a location. in the content pipeline data, this is structured as `author: Dan McCrum, text: in London and, author: Antoine Gara, text: in New York`, and the text nodes don't get any wrapper …
> fix: Remove `o3-editorial-typography-byline-location`.

- apps/dictionary/src/config/platforms/css.js
- apps/dictionary/src/config/platforms/sass.js
- apps/dictionary/src/config/platforms/tooling.js
- apps/dictionary/src/config/transformers.js
- libraries/o3-tooling-token/build/core/_variables.js
- libraries/o3-tooling-token/build/core/professional/_variables.js
- libraries/o3-tooling-token/build/internal/_variables.js
- libraries/o3-tooling-token/build/sustainable-views/_variables.js
- libraries/o3-tooling-token/build/whitelabel/_variables.js
For our sizing and typography tokens, we want to use pixel values as these are easier understood by our docs users.
This has been achieved by varying the style dictionary config for tooling and production configs.
* Use `size/px` for tooling config in Style Dictionary
> backstage: use pixel values for sizing and typography in tooling

- components/o3-foundation/src/css/components/typography/usecases.css
- components/o3-foundation/stories/story-templates.tsx
Anchor tags in wrappers need to have an `o3-typography-body-base` class somewhere in the cascade to receive text styles. 
When an anchor tag is outside another typographic tag, such as `p`, it may be necessary to apply `o3-typography-body-base` directly to the anchor tag. This class provides colour which may have precedence over any anchor styles from `o3-typography-wrapper`.
This PR adds additional selectors to typography-base classes so that anchor tags do not receive its colour styles.
> fix: exclude anchor tags from type color selectors

- components/o3-foundation/src/css/components/typography/link.css
Rather than rely on the browser default.
https://financialtimes.slack.com/archives/C07PT7A1LNB/p1742815968838199?thread_ts=1742472155.845909&cid=C07PT7A1LNB
> fix: Add explicit underline to links

- components/o3-button/README.md
- components/o3-button/main.css
- components/o3-button/src/types/index.ts
- package-lock.json
This PR adds the calendar icon as a default icon for buttons
| [CI-2665](https://financialtimes.atlassian.net/browse/CI-2665) | [Figma: Add to calendar](https://www.figma.com/design/m4B9Kn2WtXX5dz0a2pRcWa/Add-to-calendar?node-id=4019-14880&m=dev&t=RzYZ3OpIemvevsCp-1)
[CI-2665]: https://financialtimes.atlassian.net/browse/CI-2665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: calendar as default icon

- components/o-teaser/src/scss/elements/_timestamp.scss
Unreliable source order due to use of extends may be at fault
> fix: Ensure o-teaser__timestamp modifiers have higher specificity

- release-please-config.json
- scripts/regenerate-ci-config-files.js
Based on the latest [commit](https://github.com/Financial-Times/origami/commit/e00bda2104ee46cc7f99e5845dcaa8f9fd374dfe) (`e00bda2104ee46cc7f99e5845dcaa8f9fd374dfe`) on the `main` branch so that it won't kick up and release a new version for all components apart from `o3-button`.
Forgive me `release please` for this atrocity.
> chore: release please forgive me from a different engineer

- apps/dictionary/src/config/styledictionary.js
- apps/dictionary/tokens/core/use-case/color.json
- apps/dictionary/tokens/internal/use-case/color.json
- apps/dictionary/tokens/sustainable-views/use-case/color.json
- apps/dictionary/tokens/whitelabel/use-case/color.json
- components/o-private-foundation/src/scss/tokens/core.scss
- components/o-private-foundation/src/scss/tokens/internal.scss
- components/o-private-foundation/src/scss/tokens/professional.scss
- components/o-private-foundation/src/scss/tokens/sustainable-views.scss
- components/o-private-foundation/src/scss/tokens/whitelabel.scss
- components/o3-foundation/src/css/tokens/core/_variables.css
- components/o3-foundation/src/css/tokens/core/professional/_variables.css
- components/o3-foundation/src/css/tokens/internal/_variables.css
- components/o3-foundation/src/css/tokens/sustainable-views/_variables.css
- components/o3-foundation/src/css/tokens/whitelabel/_variables.css
- libraries/o3-tooling-token/build/core/_variables.js
- libraries/o3-tooling-token/build/core/professional/_variables.js
- libraries/o3-tooling-token/build/internal/_variables.js
- libraries/o3-tooling-token/build/sustainable-views/_variables.js
- libraries/o3-tooling-token/build/whitelabel/_variables.js
This aligns with our other body colour usecases, which have an inverse alternative.
I've updated our Style Dictionary config to ensure a hex is generated from a token which is a colour mix.
Tested across brands on the website locally:
> feat: Add support-inverse colour use-case.

- components/o3-button/main.css
* introduces css helper class for list icon in o3-button
* * introduces css helper class for grid icon in o3-button
> feat: introduce helper classes for o3 button grid and list icons

- components/o3-button/README.md
- components/o3-button/main.css
- components/o3-button/src/tsx/button.tsx
- components/o3-button/src/types/index.ts
The default pattern is this left placement of the icon. However, in less common cases where the icon indicates direction or continuation, the icons should be on the right.
> feat: Add option for right aligned button icons

- apps/dictionary/tokens/core/use-case/color.json
- apps/dictionary/tokens/internal/use-case/color.json
- apps/dictionary/tokens/sustainable-views/use-case/color.json
- apps/dictionary/tokens/whitelabel/use-case/color.json
- components/o-private-foundation/src/scss/tokens/core.scss
- components/o-private-foundation/src/scss/tokens/internal.scss
- components/o-private-foundation/src/scss/tokens/professional.scss
- components/o-private-foundation/src/scss/tokens/sustainable-views.scss
- components/o-private-foundation/src/scss/tokens/whitelabel.scss
- components/o3-foundation/src/css/tokens/core/_variables.css
- components/o3-foundation/src/css/tokens/core/professional/_variables.css
- components/o3-foundation/src/css/tokens/internal/_variables.css
- components/o3-foundation/src/css/tokens/sustainable-views/_variables.css
- components/o3-foundation/src/css/tokens/whitelabel/_variables.css
- libraries/o3-tooling-token/build/core/_variables.js
- libraries/o3-tooling-token/build/core/professional/_variables.js
- libraries/o3-tooling-token/build/internal/_variables.js
- libraries/o3-tooling-token/build/sustainable-views/_variables.js
- libraries/o3-tooling-token/build/whitelabel/_variables.js
Closes #2021 
_☝🏻 will autoclose the PR once this one is merged._
1. This change implements the `success-foreground` and `success-background` so it is available for use in the Origami Design Tokens and for CSS with forms.
2. It also marks `error` as deprecated with the upcoming colour audit, and to use the other two available error tokens instead.
As mentioned in a [Slack thread](https://financialtimes.slack.com/archives/G03ACR1MJ/p1743516074492649), the general consensus is to close the original PR and add in success tokens and mark the error one as deprecated due to the upcoming colours audit that Design has in mind soon.
| …
> feat: add success colour tokens

- apps/for-everyone-website/src/components/button/preview/ButtonPagination-inverse.tsx
- apps/for-everyone-website/src/components/button/preview/ButtonPagination-standard.tsx
- apps/for-everyone-website/src/content/docs/patterns/pagination.mdx
- components/o3-button/README.md
- components/o3-button/src/tsx/pagination.tsx
- components/o3-button/src/types/index.ts
- components/o3-button/stories/pagination-template.tsx
Pagination: Due to concerns with bot scraping and costs, we need to avoid the current Origami pagination pattern which includes multiple page links and a link to the last page. This impacts stream and search pages. Since it's going to impact multiple pages, we decided to quickly implement a new pagination variant in Origami with a forward/back button, and current page only. We prefer this from a reader perspective also so win win win.
This could be improved to improve efficiency – we're still calculating desktop/mobile pages to show when we're only showing the current page – and provide an api which doesn't need to know _all of the pages_ in advance. However due to time constraints and getting into a bit of a Storybook mess, I have chosen a more simple route of adding a param to the …
> feat: Add a pagination pattern to show the current page only.

- apps/dictionary/tokens/core/use-case/typography.json
- apps/dictionary/tokens/sustainable-views/use-case/typography.json
- apps/dictionary/tokens/whitelabel/use-case/typography.json
- components/o-private-foundation/src/scss/tokens/core.scss
- components/o-private-foundation/src/scss/tokens/professional.scss
- components/o-private-foundation/src/scss/tokens/sustainable-views.scss
- components/o-private-foundation/src/scss/tokens/whitelabel.scss
- components/o-teaser-collection/src/scss/_mixins.scss
- components/o-teaser/src/scss/_mixins.scss
- components/o-teaser/src/scss/elements/_default.scss
- components/o-teaser/src/scss/themes/_hero.scss
- components/o-teaser/src/scss/themes/_large.scss
- components/o-teaser/src/scss/themes/_package.scss
- components/o-teaser/src/scss/themes/_small.scss
- components/o-teaser/src/scss/themes/_standard.scss
- components/o-teaser/src/scss/themes/_top-stories.scss
- components/o-topper/src/scss/_mixins.scss
- components/o3-editorial-typography/heading.css
- components/o3-foundation/src/css/tokens/core/_variables.css
- components/o3-foundation/src/css/tokens/core/professional/_variables.css
- components/o3-foundation/src/css/tokens/sustainable-views/_variables.css
- components/o3-foundation/src/css/tokens/whitelabel/_variables.css
- libraries/o3-tooling-token/build/core/_variables.js
- libraries/o3-tooling-token/build/core/professional/_variables.js
- libraries/o3-tooling-token/build/sustainable-views/_variables.js
- libraries/o3-tooling-token/build/whitelabel/_variables.js
The design team have reported we are missing a smaller `headline` use-case for some key product areas. We believe we can reduce the size of the headlines without too big an impact.
We have had to update o-teaser and the o-editorial typography header component, which is used in article page toppers.
```
Headline small usecase reduced:
headline-sm -> scale 3 to scale 2 -> 20/24px, weight 300
headline-md -> scale 5 -> 32/32px, weight 300
headline-lg -> scale 6 -> 40/40px, weight 300
Heading component (aka topper headline):
mobile (sm) -> headline-sm to  headline-md -> 32/32px, weight 300 (increase against o2, 28/32px)
tablet (md) -> headline-md -> 32/32px, weight 300 (same as o2)
desktop (lg) -> headline-lg -> 40/40px, weight 300 (same as o2)
```
Long term, Erika (design team) would like to …
> feat: Adjust `headline` type use-case tokens.

- components/o-comments/src/js/utils/auth.js
Updating a comment that suggests something can be removed when a ticket is done, but it has other dependencies
| [CI-2644](https://financialtimes.atlassian.net/browse/CI-2644) | n/a |
[CI-2644]: https://financialtimes.atlassian.net/browse/CI-2644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci-2644 docs: update comment on response usage

- components/o3-editorial-typography/details.css
> fix: use correct editorial typography private token

- .github/workflows/o2-chromatic.yml
- README.md
- apps/astro-website/src/content/documentation/tutorials/create-a-new-component-part-6.md
- apps/o2-storybook-composition/.storybook/preview.ts
- apps/o2-storybook/.storybook/main.ts
- apps/o2-storybook/.storybook/preview.ts
- apps/o2-storybook/readme.md
- components/o-forms/src/scss/shared/_brand.scss
- components/o-forms/stories/boxRadioBtns.stories.tsx
- components/o-forms/stories/checkboxes.stories.tsx
- components/o-forms/stories/radioBtns.stories.tsx
- components/o-forms/stories/toggleCheckboxes.stories.tsx
- components/o-header-services/stories/header-services.stories.tsx
- components/o-labels/stories/internal/content.stories.tsx
- components/o-tooltip/src/scss/_brand.scss
With this PR, the following changes have been implemented:
- **Resolved `o-forms` Storybook Issue:**
The theme control option in Storybook was previously hidden because its enable/disable state depended on the `ORIGAMI_STORYBOOK_BRAND` environment variable. According to the Storybook documentation, only environment variables that start with the prefix `STORYBOOK_` can be used in story files (i.e., .jsx/.tsx files). In the `main.ts` configuration file, using `ORIGAMI_STORYBOOK_BRAND` is acceptable because its value is assigned at build time and is defined. However, in the story files, this variable is not defined. The fix changes all occurrences of `ORIGAMI_STORYBOOK_BRAND` to `STORYBOOK_BRAND` in the story files and sets the `STORYBOOK_BRAND` variable (via the `env` config option in …
> fix: o-forms theme issue

- components/o3-button/main.css
- components/o3-button/src/types/index.ts
Introduces a utility class to allow the outside-page icon to be used on o3 buttons
> feat: introduce utility class for outside page icon to o3-button

- components/o3-button/README.md
- components/o3-button/main.css
- components/o3-button/src/types/index.ts
This is used for Ask AI / FT Professional features.
I removed a list of icons from the README which was out of date. Instead rely on Storybook and the TSX template.
> feat: Add sparkles helper class for o3-button

- components/o-topper/src/scss/_elements.scss
This is causing issues for downstream apps. It is not clear why. Perhaps some source order issue because of the placeholder and/or use of at-root. It appears safe to remove the anchor colour unset as other topper themes define the colour of their links explicitly, as demoed in the screenshots below
> fix: Remove _o-topper__tag anchor colour unset

- components/o3-button/main.css
- components/o3-button/src/types/index.ts
> feat: introduce utility class for settings icon to o3-button

- components/o-topper/README.md
- components/o-topper/demos/src/basic.mustache
- components/o-topper/demos/src/branded.mustache
- components/o-topper/demos/src/centered.mustache
- components/o-topper/demos/src/deep-landscape-left.mustache
- components/o-topper/demos/src/deep-portrait.mustache
- components/o-topper/demos/src/full-bleed-image-center.mustache
- components/o-topper/demos/src/full-bleed-image-left.mustache
- components/o-topper/demos/src/full-bleed-offset-right-rail.mustache
- components/o-topper/demos/src/full-bleed-offset.mustache
- components/o-topper/demos/src/live-blog-package.mustache
- components/o-topper/demos/src/opinion.mustache
- components/o-topper/demos/src/pa11y.mustache
- components/o-topper/demos/src/package-extra.mustache
- components/o-topper/demos/src/package-special-report.mustache
- components/o-topper/demos/src/package.mustache
- components/o-topper/demos/src/podcast.mustache
- components/o-topper/demos/src/right-rail.mustache
- components/o-topper/demos/src/split-text-center.mustache
- components/o-topper/demos/src/split-text-left.mustache
- components/o-topper/src/scss/_mixins.scss
o-tooper v7 renamed classes o-topper--color-[color] to o-topper--color-o3-color-palette-[color]. This was a breaking change we did not need to make, and it was not documented in the migration guide. As we are working closely with the migration team we can safely revert this.
> fix: Revert o-topper breaking markup change

- components/o3-foundation/src/css/components/focus.css
- A button with inverse theme applied should not show a focus state on click where focus-visible is supported.
- Refactor to reduce repeated declarations.
- Apply ring focus states to any element with a class which begins with "o3" and includes "button". This includes o3-button but is more generic, making me feel warm fuzzy feelings by _technically_ avoiding a dependency (o3-foundation) knowing about its dependent (o3-button), or repeating styles in o3-button. I do foresee this potentially being helpful for other buttons like concept buttons / pills.
> fix: Improve focus styling.

- components/o-comments/README.md
- components/o-comments/src/js/comments.js
Export auth so users can be logged into Coral without also rendering the stream (to be used in Live Q&A)
https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-2617
N/A
> feat: ci-2617 export auth library for login without comments stream

- components/o-comments/main.js
Pass the export from comments.js up to main.js so we can import from `@financial-times/o-comments`, not the js file.
[JIRA ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-2617)
> fix: ci-2617 add export to main.js

- apps/o2-storybook-composition/.storybook/manager.ts
- apps/o2-storybook/.storybook/manager.ts
- apps/o3-storybook/.storybook/manager.ts
Helps visibility for people who use inverted colours to support visibility, as the default theme for components is also light.
> chore: switch default sb theme

- components/o-comments/README.md
- components/o-comments/package.json
- components/o-comments/src/js/utils/auth.js
- components/o-comments/types/index.d.ts
Adding a type declaration file for o-comments
Pushing out as a major release, because if another app also has types and they don't match, this will cause issues
[JIRA ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-2617)
> feat!: ci-2617 type declaration file for o-comments

- components/o-comments/src/js/stream.js
Found a quite old bug where options were not passed into display name prompt validation, resulting in always hitting comments API prod
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-2748)
> fix: ci-2748 pass through options to display name validation

- components/o-topper/src/scss/themes/_branded.scss
- package-lock.json
Fixes the issue where a standfirst had been copied into the summary body in spark, but summary bodies aren't accounted for when inside an opinion box with a headshot in it.
https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-2809
BEFORE - ignore the green checkmark
AFTER
> fix: ci-2809 o-topper fix text under headshot

- components/o3-button/src/types/index.ts
This adds `list` & `grid` to the allowed list for the icon helper in buttons. As we are using both in the Button Guidelines documentation.
| [OR-1499](https://financialtimes.atlassian.net/browse/OR-1499) | [Figma: Button Guidelines Review](https://www.figma.com/design/Jou5E2lLAobniGB3ZmwYSq/Button-Guidelines-Review?node-id=4208-19088&t=QRuieNC3W1CVBkQB-4) |
[OR-1499]: https://financialtimes.atlassian.net/browse/OR-1499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> feat: list / grid button icon helper

- components/o-topper/src/scss/themes/_full-bleed-image.scss
- components/o-topper/src/scss/themes/_split-text.scss
- fix: remove negative margins in o-topper
These negative margins were added in this [PR](https://github.com/Financial-Times/origami/pull/877) but with o3 they are not needed.
| JIRA ticket                                                    |
| -------------------------------------------------------------- | 
| [CPO3-188](https://financialtimes.atlassian.net/browse/CPO3-188) | 
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/ce347e0e-3207-4fe7-9667-8ccad796caab)|![image](https://github.com/user-attachments/assets/3365fade-1215-4326-a845-dc3b4922282e)|
[CPO3-188]: https://financialtimes.atlassian.net/browse/CPO3-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CPO3-188: remove negative margin in o-topper

- components/o3-social-sign-in/main.css
Aligns single-sign-in button text to center, so that it visually aligns to centered elements outside of the button.
| Before | After |
| ------- | ----- |
| <img width="565" alt="image" src="https://github.com/user-attachments/assets/9006af59-1447-48f5-a93b-a6470bbf9a27" /> | <img width="560" alt="image" src="https://github.com/user-attachments/assets/0d77592f-4443-4273-9955-9e4813e6f95e" /> |
| [OR-1721](hhttps://financialtimes.atlassian.net/browse/OR-1721) | [Figma: …
> fix: align o3-social-sign-in button text to center

- components/o3-button/src/types/index.ts
Allows the passing of `Function` type to `attributes` to allow HTML event handlers to be attached to button.
> feat: allow event handlers on o3 button attributes

- components/o3-form/package.json
- package-lock.json
> fix: move figma-sb-links to dev deps

- components/o-meter/main.scss
Makes a minor change to the `display` element to make it display correctly when using a meter element in an internal app.
This was raised by @conor-mullen for the usage of meter in https://lantern.ft.com/dashboard. This minor fix is all Conor's credit! 😅 
| [OR-1789](https://financialtimes.atlassian.net/browse/OR-1789) | N/A |
[OR-1789]: https://financialtimes.atlassian.net/browse/OR-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use -webkit-inline-block for meter inner element

- components/o-footer/src/js/footer.js
- components/o-footer/test/oFooter.test.js
since the heading is no longer interactive, it shouldn't have a `tabindex`. this was reported by DAC in [CPP-2630](https://financialtimes.atlassian.net/browse/CPP-2630).
[CPP-2630]: https://financialtimes.atlassian.net/browse/CPP-2630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove tabindex on footer headings when transitioning to large breakpoint
